[Variables]

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=SearchBar-Mike_Boynton
MyAppName=SearchBar
MyAppAuthor=Mike Boynton
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\SearchBar-Mike_Boynton\Variables\Variables.inc

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------


CustomAppName=SearchBar
CustomAppVersion=23.0429
CustomAppCreators=Mike Boynton & Cariboudjan

URLLocale1=com
URLLocale2=ca
URLLocale3=es
URLLocale4=br
URLLocale5=be

URLLocaleNum=1

Flag1=1
Flag2=2
Flag3=3
Flag4=4
Flag5=5

Name1=United States
Name2=Canada
Name3=Spain
Name4=Brazil
Name5=Belgium

CurrentInput=""

env1="Google"
env2="Duckduckgo"
env3="Bing"
env4="Yahoo"
env5="Ask"

env6="Amazon"
env7="Ebay"
env8="Bestbuy"
env9="Newegg"
env10="Etsy"

Logo1=#CURRENTPATH#Images\google.png
Logo2=#CURRENTPATH#Images\duckduckgo.png
Logo3=#CURRENTPATH#Images\bing.png
Logo4=#CURRENTPATH#Images\yahoo.png
Logo5=#CURRENTPATH#Images\ask.png

Logo6=#CURRENTPATH#Images\amazon.png
Logo7=#CURRENTPATH#Images\ebay.png
Logo8=#CURRENTPATH#Images\bestbuy.png
Logo9=#CURRENTPATH#Images\newegg.png
Logo10=#CURRENTPATH#Images\etsy.png

FlagPic1=#CURRENTPATH#Images\com.png
FlagPic2=#CURRENTPATH#Images\ca.png
FlagPic3=#CURRENTPATH#Images\es.png
FlagPic4=#CURRENTPATH#Images\br.png
FlagPic5=#CURRENTPATH#Images\be.png

CommunityAppRunOnce=1
MyAppGUID=187ab273-cb4e-4aaa-b49e-a26b869c08c0
