[Variables]

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=Feeder-Cariboudjan
MyAppName=Feeder
MyAppAuthor=Cariboudjan
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\Feeder-Cariboudjan\Variables\Variables.inc

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------

FeederRSSNum=1

ShowFeederThumbnails=1

; --------------------------------------------

FeederTitle1=This Tech Brand Will Get the Biggest Discounts During Prime Big Deal Days
FeederLink1=https://lifehacker.com/prime-day-is-best-for-exactly-one-type-of-tech-1849164435
FeederDate1=Fri, 06 Oct 2023
FeederDec1=Prime Big Deal Days is nearly here, and with it comes an avalanche of discounts and savings. While Amazon wants you to think each and every deal you come across is worth your time and attention, the truth is few of these deals are actually that great.                            
FeederImg1=

FeederTitle2=You Can Get a Lifetime Subscription to Koofr Cloud Storage for $120 Right Now
FeederLink2=https://lifehacker.com/you-can-get-a-lifetime-subscription-to-koofr-cloud-stor-1850892687
FeederDate2=Fri, 06 Oct 2023
FeederDec2=You can get a lifetime subscription with 1TB of Koofr cloud storage on sale for $119.97 right now when you use coupon code KOOFR through Oct. 15. The Koofr 1TB lifetime plan allows you to connect on unlimited desktop and mobile devices, and there’s no upload size limit or file type restrictions. It also integrates…                                  
FeederImg2=

FeederTitle3=You Can Reserve an Invite for This 50" 4K TV for $149                  
FeederLink3=https://lifehacker.com/you-can-reserve-an-invite-for-this-50-4k-tv-for-149-1850904808
FeederDate3=Fri, 06 Oct 2023
FeederDec3=Prime Big Deal Days are Oct. 10 and 11, and they’re bringing an assortment of deals—but the best deals will likely be the “invite-only” ones. These are deals that Amazon Prime members can ask to be invited to—and if you’re invited, you’ll have the opportunity to land the deal. One of those deals is this 50-inch 4K…                    
FeederImg3=

FeederTitle4=Where to Stream the LSU Vs. Missouri Game          
FeederLink4=https://lifehacker.com/where-to-watch-the-lsu-vs-missouri-game-1850905184
FeederDate4=Fri, 06 Oct 2023
FeederDec4=The LSU Tigers are traveling to Missouri this weekend to engage in spirited athletic competition with fellow SEC members the Missouri Tigers. Huzzah!              
FeederImg4=

FeederTitle5=You Can Get Five Years of AdGuard VPN for $40 Right Now        
FeederLink5=https://lifehacker.com/you-can-get-five-years-of-adguard-vpn-for-40-right-now-1850891907
FeederDate5=Fri, 06 Oct 2023
FeederDec5=AdGuard VPN makes it easy to browse more securely online, and a five-year plan is on sale for $39.97 right now. It offers unlimited data, a strict no-log policy, and currently has 4.4 out of 5 stars on the Google Play Store and 4.6 out of 5 stars on the Apple Store. AdGuard VPN is available on all platforms, both deskt…  
FeederImg5=

FeederTitle6=These New Arc Al Features Will Change How You Browse the Internet
FeederLink6=https://lifehacker.com/these-new-arc-al-features-will-change-how-you-browse-th-1850905895
FeederDate6=Fri, 06 Oct 2023
FeederDec6=AI is already integrated in popular browsers like Microsoft Edge and Opera One, and an extension will bring it to any browser. But a simple ChatGPT sidebar can only go so far. That’s why it’s cool to see the Arc browser doing something different with Arc Max, its new set of thoughtful little AI features.
            The Displace TV has started cascading itself down its zip line.                      
            The Displace TV has started cascading itself down its zip line.                      
            The Displace TV has started cascading itself down its zip line.                      
            The Displace TV has started cascading itself down its zip line.                                                    
FeederImg6=

FeederTitle7=The Out-of-Touch Adults' Guide to Kid Culture: What Is 'Locktober'?  
FeederLink7=https://lifehacker.com/the-out-of-touch-adults-guide-to-kid-culture-what-is-l-1850905693
FeederDate7=Fri, 06 Oct 2023
FeederDec7=When I hear kids talk these days, it’s like a foreign language! The hell is “locktober?” Why are they talking about “mind goblins?” What happened to speaking American, like we used to back in the good old days? The world is going to hell, I tells ya, with the kids all wearing their pants sagging down their butts and…                    
FeederImg7=

FeederTitle8=All the Yard and Garden Tasks You Should Do in October
FeederLink8=https://lifehacker.com/all-the-yard-and-garden-tasks-you-should-do-in-october-1850901896
FeederDate8=Fri, 06 Oct 2023
FeederDec8=October can be a strange month. Even when early fall dips back into summer-like temperatures, you can tell the season has changed. If light frosts haven’t set in yet, the threat of them is in the air every morning. I spend most of October rushing to harvest whatever is left in the garden and trying to wrap up all my…                
FeederImg8=
