[Variables]

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=Feeder-Cariboudjan
MyAppGUID=
MyAppName=Feeder
MyAppAuthor=Cariboudjan
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\Feeder-Cariboudjan\Variables\Variables.inc

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------

FeederRSSNum=5

ShowFeederThumbnails=1

; --------------------------------------------

FeederTitle1=Imagery Shows How a Cemetery for Russian Mercenaries Is Expanding
FeederLink1=https://www.nytimes.com/2023/01/24/world/europe/wagner-group-cemetery-russia-ukraine.html
FeederDate1=Wed, 25 Jan 2023
FeederDec1=Recent satellite imagery and video footage offer a rare look at combat fatalities sustained by the Wagner mercenary group in Ukraine.                            
FeederImg1=

FeederTitle2=Amid a Plague of Shootings, Bystanders Become Heroes
FeederLink2=https://www.nytimes.com/2023/01/25/us/shootings-guns-bystanders-civilians.html
FeederDate2=Wed, 25 Jan 2023
FeederDec2=Civilians, armed or not, have put their bodies on the line to stop gunmen. But in a nation trained to “Run, Hide, Fight,” many say it should never have come to that.                                  
FeederImg2=

FeederTitle3=A Mass Shooting in California Targeted an Entire Family                  
FeederLink3=https://www.nytimes.com/2023/01/25/us/mass-shooting-goshen-california.html
FeederDate3=Wed, 25 Jan 2023
FeederDec3=Amid an escalation in gang violence in small California towns, families have usually been spared. But gangs there are increasingly working with violent Mexican cartels.                    
FeederImg3=

FeederTitle4=2023’s Biggest, Most Unusual Race Centers on Abortion and Democracy          
FeederLink4=https://www.nytimes.com/2023/01/25/us/politics/wisconsin-supreme-court-election.html
FeederDate4=Wed, 25 Jan 2023
FeederDec4=The election for a swing seat on Wisconsin’s Supreme Court has huge policy stakes for the battleground state. Cash is pouring in, and some of the candidates have shed any pretense of judicial neutrality.              
FeederImg4=

FeederTitle5=New Lawsuit Challenges State Bans on Abortion Pills        
FeederLink5=https://www.nytimes.com/2023/01/25/health/abortion-pills-ban-genbiopro.html
FeederDate5=Wed, 25 Jan 2023
FeederDec5=The case, brought by GenBioPro, a company that makes one of two abortion drugs, argues that it is unconstitutional for a state to bar access to a medication approved by the federal government.  
FeederImg5=

FeederTitle6=Remote Workers Face a Lonely Wave of Layoffs
FeederLink6=https://www.nytimes.com/2023/01/25/business/layoffs-remote-work.html
FeederDate6=Wed, 25 Jan 2023
FeederDec6=Angst rippled across laptop screens this month, with dozens of companies announcing layoffs and finding ways to breed extra chaos in the process.                              
FeederImg6=

FeederTitle7=In U.K. Cost-of-Living Crisis, Some Workers Struggle to Feed Children  
FeederLink7=https://www.nytimes.com/2023/01/25/world/europe/uk-cost-of-living-children.html
FeederDate7=Wed, 25 Jan 2023
FeederDec7=As inflation hits the pockets of families who already had little to spare, food banks say they are getting much busier and seeing more people with jobs.                    
FeederImg7=

FeederTitle8=In ‘Shrinking,’ Jason Segel Does the Work
FeederLink8=https://www.nytimes.com/2023/01/25/arts/television/shrinking-jason-segel.html
FeederDate8=Wed, 25 Jan 2023
FeederDec8=The actor is a star, writer and executive producer of this new series about a therapist crushed by grief and trying to put himself back together. It’s a comedy.                
FeederImg8=
