[Variables]

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=Feeder-Cariboudjan
MyAppName=Feeder
MyAppAuthor=Cariboudjan
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\Feeder-Cariboudjan\Variables\Variables.inc

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------

FeederRSSNum=1

ShowFeederThumbnails=1

; --------------------------------------------

FeederTitle1=Here's When You Should (and Shouldn't) Use Silicone Grease for Household Projects
FeederLink1=https://lifehacker.com/heres-when-you-should-and-shouldnt-use-silicone-greas-1850968671
FeederDate1=Sat, 28 Oct 2023
FeederDec1=When it comes to common household tasks that require a lubricant, many people reach for products like petroleum jelly (e.g. Vaseline), cooking oil spray, or WD-40. And while they’re often effective—at least temporarily—some projects could benefit from silicone grease. Here’s what to know about the lubricant and when…                            
FeederImg1=%SKINSPATH%Droptop\Other\BackgroundProcesses\DownloadFile\FeederImg1.jpg

FeederTitle2=This Pop-Up Car Tent Is Now Less Than $300
FeederLink2=https://lifehacker.com/this-pop-up-car-tent-is-now-less-than-300-1850959395
FeederDate2=Sat, 28 Oct 2023
FeederDec2=The CARSULE pop-up cabin for your car is now through Oct. 31 on sale for $299.97 (reg. $379). This versatile tent transforms any outdoor setting—whether you’re camping, tailgating, or road tripping—into a spacious living area right at your car’s tailgate.                                    
FeederImg2=

FeederTitle3=Level Up Your Productivity With 'Time Pockets'                  
FeederLink3=https://lifehacker.com/level-up-your-productivity-with-time-pockets-1850966690
FeederDate3=Fri, 27 Oct 2023
FeederDec3=Even when you’re timeboxing your whole day, you’ll notice you end up with a few random pockets of time sprinkled throughout your schedule. If you don’t have a plan for what to do with these, they’ll become super unproductive, so start thinking of how you can maximize your productivity with “time pockets.”                    
FeederImg3=

FeederTitle4=You Can Now React to iMessages With Emojis and Stickers          
FeederLink4=https://lifehacker.com/you-can-now-react-to-imessages-with-emojis-and-stickers-1850967753
FeederDate4=Fri, 27 Oct 2023
FeederDec4=Not every text message needs a written response. If someone said something funny, you hit them with a “Haha” reaction. If you’re good with a proposed plan, reaction with a thumbs up sends the same message as, “Sounds good!”              
FeederImg4=%SKINSPATH%Droptop\Other\BackgroundProcesses\DownloadFile\FeederImg4.jpg

FeederTitle5=Yes, the FDA Really Did Issue a Warning About Black Licorice        
FeederLink5=https://lifehacker.com/fda-black-licorice-warning-1839441801
FeederDate5=Fri, 27 Oct 2023
FeederDec5=The FDA advisory about licorice is a few years old, but the memes about it will live on forever. “FDA issues warning about black licorice for halloween,” one headline read. And then below that, in a screenshot taken for posterity, somebody comments that the warning must have been “It tastes like shit.”  
FeederImg5=%SKINSPATH%Droptop\Other\BackgroundProcesses\DownloadFile\FeederImg5.jpg

FeederTitle6=I'll Take the Check, When You Have a Moment
FeederLink6=https://lifehacker.com/lifehackers-best-food-hacks-ever-1850967435
FeederDate6=Fri, 27 Oct 2023
FeederDec6=On June 2, 2015, I emailed Whitson Gordon, then editor-in-chief of Lifehacker, about a freelance writing opportunity on a fairly new, food-focused blog called “Skillet.” Eight years, five EICs, four corporate owners, at least as many CEOs, and two union contract negotiations later, I’m moving on. I’m just as surprised…                              
FeederImg6=%SKINSPATH%Droptop\Other\BackgroundProcesses\DownloadFile\FeederImg6.jpg

FeederTitle7=Hot Chicken Sliders Should Make a Football Appearance This Weekend  
FeederLink7=https://lifehacker.com/2-45-hot-chicken-slider-recipe-1850967503
FeederDate7=Fri, 27 Oct 2023
FeederDec7=Hot chicken has foodie virality at the moment, but it isn’t a passing fad. This spicy fried poultry has been searing the taste buds off of Nashvillians for generations. You can give large chicken cuts the hot chicken treatment, or shrink it down to party snack size. Bring a tiny piece of Nashville into your home with…                    
FeederImg7=%SKINSPATH%Droptop\Other\BackgroundProcesses\DownloadFile\FeederImg7.jpg

FeederTitle8=The Fastest Way to Skin an Almond
FeederLink8=https://lifehacker.com/how-to-blanch-and-skin-almonds-1849639820
FeederDate8=Fri, 27 Oct 2023
FeederDec8=You never thought the day would come. You need skinless, blanched almonds, and you need them now. You could rush over to the grocery store and pray that they have blanched almonds on the shelf, but what if they don’t? You can easily de-skin regular almonds at home in record time with a few common household items.                
FeederImg8=%SKINSPATH%Droptop\Other\BackgroundProcesses\DownloadFile\FeederImg8.jpg
