[Variables]

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=Feeder-Cariboudjan
MyAppGUID=
MyAppName=Feeder
MyAppAuthor=Cariboudjan
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\Feeder-Cariboudjan\Variables\Variables.inc

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------

FeederRSSNum=1

ShowFeederThumbnails=1

; --------------------------------------------

FeederTitle1=You Can Get a New, Open-Box Apple Magic Keyboard Folio for $99
FeederLink1=https://lifehacker.com/you-can-get-a-new-open-box-apple-magic-keyboard-folio-1850976998
FeederDate1=Thu, 02 Nov 2023
FeederDec1=This new, open-box Apple Magic Keyboard Folio for the 10th-generation iPad is on sale right now for 60% off. Its keys have a scissor mechanism that offers 1mm travel, and the QWERTY keyboard has a 14-key function row for easy keyboard shortcuts.                                  
FeederImg1=

FeederTitle2=What to Expect From Walmart's Early Black Friday Deals
FeederLink2=https://lifehacker.com/what-to-expect-from-walmarts-early-black-friday-deals-1850982935
FeederDate2=Thu, 02 Nov 2023
FeederDec2=Walmart is the third major retailer to formally and officially announce its Black Friday plans, after Target and Best Buy. Early Black Friday deals this year are good, and you should be checking them out if you haven’t already. However, make sure to shop smartly this Black Friday so you don’t end up duped or…                                  
FeederImg2=

FeederTitle3=How to Cheat on a Lie Detector Test                  
FeederLink3=https://lifehacker.com/how-to-cheat-on-a-lie-detector-test-1819793069
FeederDate3=Thu, 02 Nov 2023
FeederDec3=Welcome to Evil Week, our annual dive into all the slightly sketchy hacks we’d usually refrain from recommending. Want to weasel your way into free drinks, play elaborate mind games, or, er, launder some money? We’ve got all the info you need to be successfully unsavory.                    
FeederImg3=

FeederTitle4=You Should Move Chrome’s Address Bar to the Bottom of Your iPhone          
FeederLink4=https://lifehacker.com/you-should-move-chrome-s-address-bar-to-the-bottom-of-y-1850945219
FeederDate4=Thu, 02 Nov 2023
FeederDec4=Google Chrome on iOS has finally added one of the best features of Safari—the ability to move the address bar to the bottom of the screen. When you’re using a phone with a massive display, it’s hard to reach the top of the screen to type the name of the site. If the tab bar is at the bottom, it’s much easier to reach.                              
FeederImg4=

FeederTitle5=All the New Ways to Use Your Apple Watch        
FeederLink5=https://lifehacker.com/all-the-new-ways-to-use-your-apple-watch-1850984316
FeederDate5=Thu, 02 Nov 2023
FeederDec5=With watchOS 10, Apple breathed new life into the Apple Watch, without even changing the hardware design. Now, watchOS finally embraces buttons, and higher information density across the board. Most importantly, in my view, are widgets, which have the potential to change how you interact with your Apple Watch for the…  
FeederImg5=

FeederTitle6=You Can Fix These Common Hot Water Heater Problems Yourself
FeederLink6=https://lifehacker.com/you-can-fix-these-common-hot-water-heater-problems-your-1850982530
FeederDate6=Thu, 02 Nov 2023
FeederDec6=Hot water heaters might seem too complicated and intimidating to fix. They have plumbing and electrical components—two things that usually signal that hiring a pro is the best choice when you need help. While this is true for bigger problems, there are some common maintenance and repair tasks that you can do yourself…
            The Displace TV has started cascading itself down its zip line.                      
            The Displace TV has started cascading itself down its zip line.                      
            The Displace TV has started cascading itself down its zip line.                      
            The Displace TV has started cascading itself down its zip line.                                                    
FeederImg6=

FeederTitle7=Evil Week: 20 Unethical (but Brilliant) Life Hacks From Reddit  
FeederLink7=https://lifehacker.com/20-unethical-but-brilliant-life-hacks-from-reddit-1847783281
FeederDate7=Thu, 02 Nov 2023
FeederDec7=Welcome to Evil Week, our annual dive into all the slightly sketchy hacks we’d usually refrain from recommending. Want to weasel your way into free drinks, play elaborate mind games, or, er, launder some money? We’ve got all the info you need to be successfully unsavory.                    
FeederImg7=

FeederTitle8=Today’s NYT Connections Hints (and Answer) for Thursday, November 2, 2023
FeederLink8=https://lifehacker.com/nyt-connections-answer-today-november-2-2023-1850980019
FeederDate8=Thu, 02 Nov 2023
FeederDec8=Ready for some INTEL on today’s computer-brand-studded board? If you’re looking for the Connections answer for Thursday, November 2, 2023, read on—I’ll share some clues, tips, and strategies, and finally the solutions to all four categories. Along the way, I’ll explain the meanings of the trickier words and we’ll…                
FeederImg8=
