[Variables]
; -------------------------------------------------------------------------------
; VariablesDefault.inc should contain all or most of the variables required for the app's function, especially user settings.
; VariablesDefault.inc keys and values are the default settings when the app is first installed or reinstalled.
; Any settings changed by the user should be written to Variables.in, not VariablesDefault.inc.
; All keys in Variables.inc supercede the identical keys of VariablesDefault.inc. 
; VariablesDefault.inc acts as a backup and fallback.
; -------------------------------------------------------------------------------

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=PC_Scanner-TheyCallMePapa
MyAppName=PC Scanner
MyAppAuthor=TheyCallMePapa
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\PC_Scanner-TheyCallMePapa\Variables\Variables.inc
MyAppGUID=ff58fa91-8d06-4a81-8ede-c778621bd713

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------
