[Variables]

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=JaxCore-Jax
MyAppName=JaxCore
MyAppAuthor=Jax
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\JaxCore-Jax\Variables\Variables.inc

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------

DroptopIntegration=0

ShowHideJaxButtonApp=0
MyAppGUID=496df783-165f-48a5-b924-df5422b01fb7
