chcp 1256

@echo off

set gamesfol2="Campaign"
set gamesfol3="Casual"
set gamesfol4="Indie"
set gamesfol5="ÇßËÑ ãä áÇÚÈ ÇáãÍãáÉ"
set gamesfol6="ÇßËÑ ãä áÇÚÈ İí ÇáÅäÊÑäÊ"
set gamesfol7="ãÍÇßÇÉ"
set gamesfol8="ÇáÑíÇÖÉ æÇáÓÈÇŞÇÊ"
set gamesfol9="ÇáæÇŞÚ ÇáÇİÊÑÇÖí"
set gamescamfol1="Action"
set gamescamfol2="ÑÚÈ"
set gamescamfol3="ÇÓÊÑÎÇÁ"
set gamescamfol4="RPG"
set gamescamfol5="äÌÇÉ"
set gameslocfol1="ÊÚÇæäí"
set gameslocfol2="Íİá"
set gameslocfol3="Versus"
set gamesonlfol1="ÇáãÚÑßÉ ÇáãáßíÉ"
set gamesonlfol2="MMO"
set gamesonlfol3="ÇáÑÇãí"
set gamesonlfol4="ÅÓÊÑÇÊíÌíÉ"

set newsmediafol1="ÃŞÕì ÇáíÓÇÑ"
set newsmediafol2="ÇŞÕì Çáíãíä"
set newsmediafol3="İí ÇáæÓØ"

set onlinetools1fol="ÇáÊÔÎíÕ"

set podcastsfol1="ÇáÏÑÇãÇ æÇáÌÑíãÉ"
set podcastsfol2="Past & Present"
set podcastsfol3="ÓíÇÓÉ"
set podcastsfol4="ÇáÚáæã æÇáÊßäæáæÌíÇ"
set podcastsfol5="ÇáÌäÓ æÚáã ÇáäİÓ"
set podcastsfol6="ÑíÇÖÇÊ"
set podcastsfol7="ÈÑäÇãÌ ÍæÇÑí"

set bookmarksfol1="æÓÇÆá ÇáÅÚáÇã"
set bookmarksfol2="ÃÏæÇÊ Úáì ÇáÅäÊÑäÊ"
set bookmarksfol3="ÇáãÏæäÉ ÇáÕæÊíÉ"
set bookmarksfol4="ÇáÊÓæŞ"
set bookmarks2="Gmail"
set bookmarks3="Google Keep"
set bookmarks4="Google Maps"
set bookmarks5="Google Photos"
set bookmarks6="Disney+"
set bookmarks7="Netflix"
set bookmarks8="Reddit"
set bookmarks9="Steam"
set bookmarks10="Twitch"
set bookmarks11="YouTube"

set advanced1="ãæÌå ÇáÃãÑ"
set advanced2="ãÏíÑ ÇáÌåÇÒ"
set advanced3="Disk cleanup"
set advanced4="Disk management"
set advanced5="ãÍÑÑ ÓÌá ÇáäÙÇã"
set advanced6="ãÑÇŞÈ ÇáãæÑÏ"
set advanced7="ÊØÈíŞÇÊ ÈÏÁ ÇáÊÔÛíá"
set advanced8="ãÓÇÍÇÊ ÇáÊÎÒíä"
set advanced9="ÃÚÏÇÏÇÊ ÇáäÙÇã"
set advanced10="ÌÏÇÑ ÍãÇíÉ æíäÏæÒ"
set advanced11="æÇÌåÉ ÇæÇãÑ æíäÏæÒ"
set advanced12="ÎÏãÇÊ æíäÏæÒ"

set controlfol1="ÖæÇÈØ ãÊŞÏãÉ"
set control1="ÎáİíÉ ÓØÍ ÇáãßÊÈ"
set control2="ÇÚÏÇÏÇÊ ÇáÚÑÖ"
set control3="ÊßÈíÑ"
set control4="áæÍÉ ãİÇÊíÍ Úáì ÇáÔÇÔÉ"
set control5="ÎíÇÑÇÊ ÇáØÇŞÉ"
set control6="ÓáÉ ÇáãåãáÇÊ"
set control7="ÚÑÖ ÇáÊÈÏíá"
set control8="ãÚáæãÇÊ ÇáäÙÇã"
set control9="ãÏíÑ ÇáãåÇã"
set control10="ÇáÛÇÁ ÊäÕíÈ ÈÑäÇãÌ"
set control11="ÍÓÇÈÇÊ ÇáãÓÊÎÏãíä"

cd %~dp0

call "RenameShortcuts.bat"