gamesfol2=Campaign
gamesfol3=Casual
gamesfol4=Indie
gamesfol5=ÇßËÑ ãä áÇÚÈ ÇáãÍãáÉ
gamesfol6=ÇßËÑ ãä áÇÚÈ İí ÇáÅäÊÑäÊ
gamesfol7=ãÍÇßÇÉ
gamesfol8=ÇáÑíÇÖÉ æÇáÓÈÇŞÇÊ
gamesfol9=ÇáæÇŞÚ ÇáÇİÊÑÇÖí
gamescamfol1=Action
gamescamfol2=ÑÚÈ
gamescamfol3=ÇÓÊÑÎÇÁ
gamescamfol4=RPG
gamescamfol5=äÌÇÉ
gameslocfol1=ÊÚÇæäí
gameslocfol2=Íİá
gameslocfol3=Versus
gamesonlfol1=ÇáãÚÑßÉ ÇáãáßíÉ
gamesonlfol2=MMO
gamesonlfol3=ÇáÑÇãí
gamesonlfol4=ÅÓÊÑÇÊíÌíÉ

newsmediafol1=ÃŞÕì ÇáíÓÇÑ
newsmediafol2=ÇŞÕì Çáíãíä
newsmediafol3=İí ÇáæÓØ

onlinetools1fol=ÇáÊÔÎíÕ

podcastsfol1=ÇáÏÑÇãÇ æÇáÌÑíãÉ
podcastsfol2=Past & Present
podcastsfol3=ÓíÇÓÉ
podcastsfol4=ÇáÚáæã æÇáÊßäæáæÌíÇ
podcastsfol5=ÇáÌäÓ æÚáã ÇáäİÓ
podcastsfol6=ÑíÇÖÇÊ
podcastsfol7=ÈÑäÇãÌ ÍæÇÑí

bookmarksfol1=æÓÇÆá ÇáÅÚáÇã
bookmarksfol2=ÃÏæÇÊ Úáì ÇáÅäÊÑäÊ
bookmarksfol3=ÇáãÏæäÉ ÇáÕæÊíÉ
bookmarksfol4=ÇáÊÓæŞ
bookmarks2=Gmail
bookmarks3=Google Keep
bookmarks4=Google Maps
bookmarks5=Google Photos
bookmarks6=Disney+
bookmarks7=Netflix
bookmarks8=Reddit
bookmarks9=Steam
bookmarks10=Twitch
bookmarks11=YouTube

advanced1=ãæÌå ÇáÃãÑ
advanced2=ãÏíÑ ÇáÌåÇÒ
advanced3=Disk cleanup
advanced4=Disk management
advanced5=ãÍÑÑ ÓÌá ÇáäÙÇã
advanced6=ãÑÇŞÈ ÇáãæÑÏ
advanced7=ÊØÈíŞÇÊ ÈÏÁ ÇáÊÔÛíá
advanced8=ãÓÇÍÇÊ ÇáÊÎÒíä
advanced9=ÃÚÏÇÏÇÊ ÇáäÙÇã
advanced10=ÌÏÇÑ ÍãÇíÉ æíäÏæÒ
advanced11=æÇÌåÉ ÇæÇãÑ æíäÏæÒ
advanced12=ÎÏãÇÊ æíäÏæÒ

controlfol1=ÖæÇÈØ ãÊŞÏãÉ
control1=ÎáİíÉ ÓØÍ ÇáãßÊÈ
control2=ÇÚÏÇÏÇÊ ÇáÚÑÖ
control3=ÊßÈíÑ
control4=áæÍÉ ãİÇÊíÍ Úáì ÇáÔÇÔÉ
control5=ÎíÇÑÇÊ ÇáØÇŞÉ
control6=ÓáÉ ÇáãåãáÇÊ
control7=ÚÑÖ ÇáÊÈÏíá
control8=ãÚáæãÇÊ ÇáäÙÇã
control9=ãÏíÑ ÇáãåÇã
control10=ÇáÛÇÁ ÊäÕíÈ ÈÑäÇãÌ
control11=ÍÓÇÈÇÊ ÇáãÓÊÎÏãíä