gamesfol2=Kampagne
gamesfol3=Gelegenheitsspiele
gamesfol4=Indiespiele
gamesfol5=Local multiplayer
gamesfol6=Online multiplayer
gamesfol7=Simulationsspiele
gamesfol8=Sport & Rennspiele
gamesfol9=Virtual Reality
gamescamfol1=Action
gamescamfol2=Horror
gamescamfol3=Entspannung
gamescamfol4=RPG
gamescamfol5=Survival
gameslocfol1=Co-op
gameslocfol2=Party
gameslocfol3=Versus
gamesonlfol1=Battle Royale
gamesonlfol2=MMO
gamesonlfol3=Shooter
gamesonlfol4=Strategie

newsmediafol1=Ganz links
newsmediafol2=Ganz rechts
newsmediafol3=International

onlinetools1fol=Diagnose

podcastsfol1=Krimie & Drama
podcastsfol2=Past & Present
podcastsfol3=Politik
podcastsfol4=Wirtschaft & Technologie
podcastsfol5=Sex & Psychologie
podcastsfol6=Sport
podcastsfol7=Talk shows

bookmarksfol1=Neuigkeiten & Media
bookmarksfol2=Online tools
bookmarksfol3=Spotify Podcasts
bookmarksfol4=Shopping
bookmarks2=Gmail
bookmarks3=Google Keep
bookmarks4=Google Maps
bookmarks5=Google Photos
bookmarks6=Disney+
bookmarks7=Netflix
bookmarks8=Reddit
bookmarks9=Steam
bookmarks10=Twitch
bookmarks11=YouTube

advanced1=Eingabeaufforderung
advanced2=Geräte-Manager
advanced3=Datenträgerbereinigung
advanced4=Festplattenmanagement
advanced5=Registry Editor
advanced6=Ressourcenmonitor
advanced7=Autostart Programme
advanced8=Speicherplatz
advanced9=System Konfiguration
advanced10=Windows Firewall
advanced11=Windows PowerShell
advanced12=Windows Systemdienst

controlfol1=Erweiterte Einstellungen
control1=Desktop Hintergrund
control2=Bildschirmeinstellungen
control3=Vergrößern
control4=On-screen Tastatur
control5=Powerplan Optionen
control6=Papierkorb
control7=Display wechseln
control8=System Informationen
control9=Task Manager
control10=Programm deinstallieren
control11=Benutzer Accounts