gamesfol2=Campaign
gamesfol3=Casual
gamesfol4=Indie
gamesfol5=Local multiplayer
gamesfol6=Online multiplayer
gamesfol7=Simulation
gamesfol8=Sport & racing
gamesfol9=Virtual Reality
gamescamfol1=Action
gamescamfol2=Horror
gamescamfol3=Relaxed
gamescamfol4=RPG
gamescamfol5=Survival
gameslocfol1=Co-op
gameslocfol2=Party
gameslocfol3=Versus
gamesonlfol1=Battle Royale
gamesonlfol2=MMO
gamesonlfol3=Shooter
gamesonlfol4=Strategy

newsmediafol1=Far-Left
newsmediafol2=Far-Right
newsmediafol3=International

onlinetools1fol=Diagnostic

podcastsfol1=Crime & Drama
podcastsfol2=Past & Present
podcastsfol3=Politics
podcastsfol4=Science & Technology
podcastsfol5=Sex & Psychology
podcastsfol6=Sport
podcastsfol7=Talk shows

bookmarksfol1=News & media
bookmarksfol2=Online tools
bookmarksfol3=Spotify Podcasts
bookmarksfol4=Shopping
bookmarks2=Gmail
bookmarks3=Google Keep
bookmarks4=Google Maps
bookmarks5=Google Photos
bookmarks6=Disney+
bookmarks7=Netflix
bookmarks8=Reddit
bookmarks9=Steam
bookmarks10=Twitch
bookmarks11=YouTube

advanced1=Command prompt
advanced2=Device manager
advanced3=Disk cleanup
advanced4=Disk management
advanced5=Registry editor
advanced6=Resource monitor
advanced7=Startup apps
advanced8=Storage spaces
advanced9=System configuration
advanced10=Windows firewall
advanced11=Windows PowerShell
advanced12=Windows services

controlfol1=Advanced controls
control1=Desktop background
control2=Display settings
control3=Magnify
control4=On-screen keyboard
control5=Power options
control6=Recycle bin
control7=Switch display
control8=System information
control9=Task manager
control10=Uninstall a program
control11=User accounts