gamesfol2=Campaña
gamesfol3=Casual
gamesfol4=Indie
gamesfol5=Multijugador local
gamesfol6=Multijugador en línea
gamesfol7=Simulación
gamesfol8=Deportes y carreras
gamesfol9=Realidad virtual
gamescamfol1=Acción
gamescamfol2=Horror
gamescamfol3=Relajado
gamescamfol4=RPG
gamescamfol5=Supervivencia
gameslocfol1=Cooperativo
gameslocfol2=Fiesta
gameslocfol3=Versus
gamesonlfol1=Battle royale
gamesonlfol2=MMO
gamesonlfol3=Disparos
gamesonlfol4=Estrategia

newsmediafol1=Extremo izquierdo
newsmediafol2=Extremo derecho
newsmediafol3=Internacional

onlinetools1fol=Diagnóstico

podcastsfol1=Crimen y drama
podcastsfol2=Past & Present
podcastsfol3=Política
podcastsfol4=Ciencia y Tecnología
podcastsfol5=Sexo y Psicología
podcastsfol6=Deportes
podcastsfol7=Talk Shows

bookmarksfol1=Noticias y medios
bookmarksfol2=Herramientas en línea
bookmarksfol3=Spotify Podcasts
bookmarksfol4=Compras
bookmarks2=Gmail
bookmarks3=Google Keep
bookmarks4=Google Maps
bookmarks5=Google Photos
bookmarks6=Disney+
bookmarks7=Netflix
bookmarks8=Reddit
bookmarks9=Steam
bookmarks10=Twitch
bookmarks11=YouTube

advanced1=Símbolo del sistema
advanced2=Admin. de dispositivos
advanced3=Limpieza de disco
advanced4=Administración de discos
advanced5=Editor del registro
advanced6=Monitor de recursos
advanced7=Apps de arranque
advanced8=Espacios de almac.
advanced9=Config. del sistema
advanced10=Firewall de Windows
advanced11=Windows PowerShell
advanced12=Servicios de Windows

controlfol1=Controles avanzados
control1=Fondo de escritorio
control2=Conf. de pantalla
control3=Lupa
control4=Teclado en pantalla
control5=Opciones de poder
control6=Papelera de reciclaje
control7=Cambiar pantalla
control8=Info. del sistema
control9=Admin. de tareas
control10=Desinstalar un programa
control11=Usuarios