gamesfol2=˜ãíä
gamesfol3=ÚÇÏí
gamesfol4=ãÓÊŞá
gamesfol5=äÏäİÑå ãÍáí
gamesfol6=äÏäİÑå ÂäáÇíä
gamesfol7=ÔÈíå ÓÇÒí
gamesfol8=æÑÒÔí æ ãÓÇÈŞå Çí
gamesfol9=æÇŞÚíÊ ãÌÇÒí
gamescamfol1=Ç˜Ôä
gamescamfol2=ÊÑÓäÇ˜
gamescamfol3=ÂÑÇã
gamescamfol4=äŞÔ ÂİÑíäí
gamescamfol5=ÈŞÇ
gameslocfol1=ÏæäİÑå
gameslocfol2=Ñæåí
gameslocfol3=ÊŞÇÈáí
gamesonlfol1=ÈÊá ÑæíÇá
gamesonlfol2=äÏäİÑå æÓíÚ
gamesonlfol3=ÊíÑÇäÏÇÒí
gamesonlfol4=ÇÓÊÑÇÊí˜

newsmediafol1=ÇÕáÇÍ ØáÈ
newsmediafol2=ÇÕæá ÑÇ
newsmediafol3=íä Çáãááí

onlinetools1fol=ÚíÈ íÇÈí

podcastsfol1=ÌÑã æ ÌäÇíí
podcastsfol2=Past & Present
podcastsfol3=ÓíÇÓí
podcastsfol4=Úáãí æ Ê˜äæáæí
podcastsfol5=ÌäÓí æ ÑæÇäÔäÇÓí
podcastsfol6=æÑÒÔí
podcastsfol7=ÊÇ˜ Ôæ åÇ

bookmarksfol1=ÇÎÈÇÑ æ ÑÓÇäå
bookmarksfol2=ÇÈÒÇÑ ÂäáÇíä
bookmarksfol3=ÇÏ˜ÓÊ åÇ
bookmarksfol4=ÎÑíÏ
bookmarks2=Ìíãíá
bookmarks3=æá ˜í
bookmarks4=æá ã
bookmarks5=æá İæÊæ
bookmarks6=åæáæ
bookmarks7=äÊİáí˜Ó
bookmarks8=ÑÏíÊ
bookmarks9=ÇÓÊíã
bookmarks10=Êæíí
bookmarks11=íæÊíæÈ

advanced1=ÎØ İÑãÇä
advanced2=ãÏíÑíÊ ÏÓÊÇå åÇ
advanced3=Ç˜ ÓÇÒí ÏíÓ˜
advanced4=ãÏíÑíÊ ÏíÓ˜
advanced5=æíÑÇíÔÑ ÑÌíÓÊÑí
advanced6=ãÇäíÊæÑ ãäÇÈÚ
advanced7=ÈÑäÇãå åÇí ÇÓÊÇÑ Â
advanced8=İÖÇåÇí ĞÎíÑå ÓÇÒí
advanced9=ÊäÙíãÇÊ ÓíÓÊã
advanced10=İÇíÑæÇá æíäÏæÒ
advanced11=æíäÏæÒ ÇæÑÔá
advanced12=ÓÑæíÓ åÇí æíäÏæÒ

controlfol1=ÊäÙíãÇÊ ÍÑİå Çí
control1=Ó Òãíäå åÇí ÏÓ˜ÊÇ
control2=ÊäÙíãÇÊ äãÇíÔÑ
control3=ĞÑå Èíä
control4=˜íÈæÑÏ ãÌÇÒí
control5=ÊäÙíãÇÊ ÇæÑ
control6=ÓØá ÂÔÛÇá
control7=ÊÛííÑ äãÇíÔÑ
control8=ÇØáÇÚÊ ÓíÓÊã
control9=ÊÓ˜ ãäíÌÑ
control10=Ç˜ÓÇÒí ÈÑäÇãå
control11=ÍÓÇÈ åÇí ˜ÇÑÈÑí