gamesfol2=Campagne
gamesfol3=DÈcontractÈ
gamesfol4=IndÈpendant
gamesfol5=Multijoueur local
gamesfol6=Multijoueur en ligne
gamesfol7=Simulation
gamesfol8=Sports et courses
gamesfol9=RÈalitÈ virtuelle
gamescamfol1=Action
gamescamfol2=Horreur
gamescamfol3=DÈtendu
gamescamfol4=RPG
gamescamfol5=Survie
gameslocfol1=CoopÈrative
gameslocfol2=FÍte
gameslocfol3=Contre
gamesonlfol1=Bataille royale
gamesonlfol2=MMO
gamesonlfol3=Tireur
gamesonlfol4=StratÈgie

newsmediafol1=Far-Left
newsmediafol2=Far-Right
newsmediafol3=Internationale

onlinetools1fol=Diagnostic

podcastsfol1=Crime & drame
podcastsfol2=Past & Present
podcastsfol3=Politique
podcastsfol4=Science & technologie
podcastsfol5=Sexe & psychologie
podcastsfol6=Sports
podcastsfol7=Talk shows

bookmarksfol1=ActualitÇs et mÇdias
bookmarksfol2=Outils en ligne
bookmarksfol3=Spotify Podcasts
bookmarksfol4=Shopping
bookmarks2=Gmail
bookmarks3=Google Keep
bookmarks4=Google Maps
bookmarks5=Google Photos
bookmarks6=Disney+
bookmarks7=Netflix
bookmarks8=Reddit
bookmarks9=Steam
bookmarks10=Twitch
bookmarks11=YouTube

advanced1=Invite de commande
advanced2=Gestionnaire de pÇriph.
advanced3=Nettoyage de disque
advanced4=Gestionnaire de disque
advanced5=êditeur de registre
advanced6=Moniteur de ressources
advanced7=Apps. de dÇmarrage
advanced8=Espaces de stockage
advanced9=Configuration du syst√®me
advanced10=Windows firewall
advanced11=Windows PowerShell
advanced12=Windows services

controlfol1=Contrìles avancÇs
control1=Fond d'Çcran
control2=Paramätres d'affichage
control3=Magnifier
control4=Sur clavier de l'Çcran
control5=Options d'alimentation
control6=Corbeille
control7=Commutateur d'affichage
control8=Informations systäme
control9=Gestionnaire des tÉches
control10=DÇsinstaller un progr.
control11=Comptes utilisateur