chcp 863

@echo off

set gamesfol2="Campagne"
set gamesfol3="DÈcontractÈ"
set gamesfol4="IndÈpendant"
set gamesfol5="Multijoueur local"
set gamesfol6="Multijoueur en ligne"
set gamesfol7="Simulation"
set gamesfol8="Sports et courses"
set gamesfol9="RÈalitÈ virtuelle"
set gamescamfol1="Action"
set gamescamfol2="Horreur"
set gamescamfol3="DÈtendu"
set gamescamfol4="RPG"
set gamescamfol5="Survie"
set gameslocfol1="CoopÈrative"
set gameslocfol2="FÍte"
set gameslocfol3="Contre"
set gamesonlfol1="Bataille royale"
set gamesonlfol2="MMO"
set gamesonlfol3="Tireur"
set gamesonlfol4="StratÈgie"

set newsmediafol1="Far-Left"
set newsmediafol2="Far-Right"
set newsmediafol3="Internationale"

set onlinetools1fol="Diagnostic"

set podcastsfol1="Crime & drame"
set podcastsfol2="Past & Present"
set podcastsfol3="Politique"
set podcastsfol4="Science & technologie"
set podcastsfol5="Sexe & psychologie"
set podcastsfol6="Sports"
set podcastsfol7="Talk shows"

set bookmarksfol1="ActualitÇs et mÇdias"
set bookmarksfol2="Outils en ligne"
set bookmarksfol3="Spotify Podcasts"
set bookmarksfol4="Shopping"
set bookmarks2="Gmail"
set bookmarks3="Google Keep"
set bookmarks4="Google Maps"
set bookmarks5="Google Photos"
set bookmarks6="Disney+"
set bookmarks7="Netflix"
set bookmarks8="Reddit"
set bookmarks9="Steam"
set bookmarks10="Twitch"
set bookmarks11="YouTube"

set advanced1="Invite de commande"
set advanced2="Gestionnaire de pÇriph."
set advanced3="Nettoyage de disque"
set advanced4="Gestionnaire de disque"
set advanced5="êditeur de registre"
set advanced6="Moniteur de ressources"
set advanced7="Apps. de dÇmarrage"
set advanced8="Espaces de stockage"
set advanced9="Configuration du syst√®me"
set advanced10="Windows firewall"
set advanced11="Windows PowerShell"
set advanced12="Windows services"

set controlfol1="Contrìles avancÇs"
set control1="Fond d'Çcran"
set control2="Paramätres d'affichage"
set control3="Magnifier"
set control4="Sur clavier de l'Çcran"
set control5="Options d'alimentation"
set control6="Corbeille"
set control7="Commutateur d'affichage"
set control8="Informations systäme"
set control9="Gestionnaire des tÉches"
set control10="DÇsinstaller un progr."
set control11="Comptes utilisateur"

cd %~dp0

call "RenameShortcuts.bat"