gamesfol2=Kampanye
gamesfol3=Kasual
gamesfol4=Indie
gamesfol5=Multiplayer lokal
gamesfol6=Multiplayer daring
gamesfol7=Simulasi
gamesfol8=Olahraga & balapan
gamesfol9=Realitas virtual
gamescamfol1=Aksi
gamescamfol2=Horror
gamescamfol3=Santai
gamescamfol4=RPG
gamescamfol5=Bertahan hidup
gameslocfol1=Kerjasama
gameslocfol2=Pesta
gameslocfol3=Lawan
gamesonlfol1=Battle Royale
gamesonlfol2=MMO
gamesonlfol3=Tembak-tembakan
gamesonlfol4=Strategi

newsmediafol1=Kiri-jauh
newsmediafol2=Kanan-jauh
newsmediafol3=Internasional

onlinetools1fol=Diagnostik

podcastsfol1=Kejahatan & Drama
podcastsfol2=Dulu & Sekarang
podcastsfol3=Politik
podcastsfol4=Sains & Teknologi
podcastsfol5=Seks & Psikologi
podcastsfol6=Olahraga
podcastsfol7=Acara bincang-bincang

bookmarksfol1=Berita & media
bookmarksfol2=Alat daring
bookmarksfol3=Podcast Spotify
bookmarksfol4=Belanja
bookmarks2=Gmail
bookmarks3=Google Keep
bookmarks4=Google Maps
bookmarks5=Google Photos
bookmarks6=Disney+
bookmarks7=Netflix
bookmarks8=Reddit
bookmarks9=Steam
bookmarks10=Twitch
bookmarks11=YouTube

advanced1=Prompt perintah
advanced2=Pengelola perangkat
advanced3=Pembersihan disk
advanced4=Manajemen disk
advanced5=Pengedit registri
advanced6=Monitor sumber daya
advanced7=Aplikasi startup
advanced8=Ruang penyimpanan
advanced9=Konfigurasi sistem
advanced10=Windows Firewall
advanced11=Windows PowerShell
advanced12=Layanan windows

controlfol1=Kontrol lanjutan
control1=Latar belakang desktop
control2=Pengaturan tampilan
control3=Perbesar
control4=Papan ketik di layar
control5=Opsi sumber daya
control6=Tempat sampah
control7=Alihkan tampilan
control8=Informasi sistem
control9=Pengelola tugas
control10=Copot pemasangan program
control11=Akun pengguna