chcp 437

@echo off

set gamesfol2="Kampanye"
set gamesfol3="Kasual"
set gamesfol4="Indie"
set gamesfol5="Multiplayer lokal"
set gamesfol6="Multiplayer daring"
set gamesfol7="Simulasi"
set gamesfol8="Olahraga & balapan"
set gamesfol9="Realitas virtual"
set gamescamfol1="Aksi"
set gamescamfol2="Horror"
set gamescamfol3="Santai"
set gamescamfol4="RPG"
set gamescamfol5="Bertahan hidup"
set gameslocfol1="Kerjasama"
set gameslocfol2="Pesta"
set gameslocfol3="Lawan"
set gamesonlfol1="Battle Royale"
set gamesonlfol2="MMO"
set gamesonlfol3="Tembak-tembakan"
set gamesonlfol4="Strategi"

set newsmediafol1="Kiri-jauh"
set newsmediafol2="Kanan-jauh"
set newsmediafol3="Internasional"

set onlinetools1fol="Diagnostik"

set podcastsfol1="Kejahatan & Drama"
set podcastsfol2="Dulu & Sekarang"
set podcastsfol3="Politik"
set podcastsfol4="Sains & Teknologi"
set podcastsfol5="Seks & Psikologi"
set podcastsfol6="Olahraga"
set podcastsfol7="Acara bincang-bincang"

set bookmarksfol1="Berita & media"
set bookmarksfol2="Alat daring"
set bookmarksfol3="Podcast Spotify"
set bookmarksfol4="Belanja"
set bookmarks2="Gmail"
set bookmarks3="Google Keep"
set bookmarks4="Google Maps"
set bookmarks5="Google Photos"
set bookmarks6="Disney+"
set bookmarks7="Netflix"
set bookmarks8="Reddit"
set bookmarks9="Steam"
set bookmarks10="Twitch"
set bookmarks11="YouTube"

set advanced1="Prompt perintah"
set advanced2="Pengelola perangkat"
set advanced3="Pembersihan disk"
set advanced4="Manajemen disk"
set advanced5="Pengedit registri"
set advanced6="Monitor sumber daya"
set advanced7="Aplikasi startup"
set advanced8="Ruang penyimpanan"
set advanced9="Konfigurasi sistem"
set advanced10="Windows Firewall"
set advanced11="Windows PowerShell"
set advanced12="Layanan windows"

set controlfol1="Kontrol lanjutan"
set control1="Latar belakang desktop"
set control2="Pengaturan tampilan"
set control3="Perbesar"
set control4="Papan ketik di layar"
set control5="Opsi sumber daya"
set control6="Tempat sampah"
set control7="Alihkan tampilan"
set control8="Informasi sistem"
set control9="Pengelola tugas"
set control10="Copot pemasangan program"
set control11="Akun pengguna"

cd %~dp0

call "RenameShortcuts.bat"