gamesfol2=Campagna
gamesfol3=Casual
gamesfol4=Indie
gamesfol5=Multiplayer Locali
gamesfol6=Multiplayer Online
gamesfol7=Simulazione
gamesfol8=Sport & Corse
gamesfol9=Realtà Virtuale
gamescamfol1=Azione
gamescamfol2=Horror
gamescamfol3=Rilassanti
gamescamfol4=RPG
gamescamfol5=Sopravvivenza
gameslocfol1=Co-op
gameslocfol2=Party
gameslocfol3=Versus
gamesonlfol1=Battle Royale
gamesonlfol2=MMO
gamesonlfol3=Sparatutto
gamesonlfol4=Strategia

newsmediafol1=Di Sinistra
newsmediafol2=Di Destra
newsmediafol3=Internazionale

onlinetools1fol=Diagnostica

podcastsfol1=Crime & Dramma
podcastsfol2=Past & Present
podcastsfol3=Politica
podcastsfol4=Scienza & Tecnologia
podcastsfol5=Sesso & Psicologia
podcastsfol6=Sport
podcastsfol7=Talk Show

bookmarksfol1=Notizie & Media
bookmarksfol2=Strumenti Online
bookmarksfol3=Podcast
bookmarksfol4=Shopping
bookmarks2=Gmail
bookmarks3=Google Keep
bookmarks4=Google Maps
bookmarks5=Google Photos
bookmarks6=Disney+
bookmarks7=Netflix
bookmarks8=Reddit
bookmarks9=Steam
bookmarks10=Twitch
bookmarks11=YouTube

advanced1=Prompt dei Comandi
advanced2=Gestore Dispositivi
advanced3=Pulizia del Disco
advanced4=Gestore dei Dischi
advanced5=Editor del Registro
advanced6=Monitor delle Risorse
advanced7=App all'Avvio
advanced8=Spazi di Archiviazione
advanced9=Configurazione di Sistema
advanced10=Firewall di Windows
advanced11=Powershell di Windows
advanced12=Servizi di Windows

controlfol1=Controlli avanzati
control1=Sfondi Desktop
control2=Impostazioni Display
control3=Ingrandisci
control4=Tastiera sullo schermo
control5=Opzioni di alimentazione
control6=Cestino
control7=Cambia display
control8=Informazioni di Sistema
control9=Task Manager
control10=Disinstalla un programma
control11=Account Utente