gamesfol2=キャンペーン
gamesfol3=カジュアル
gamesfol4=インディーズ
gamesfol5=ローカルマルチプレイ
gamesfol6=オンラインマルチプレイヤー
gamesfol7=シミュレーション
gamesfol8=スポーツ＆レーシング
gamesfol9=バーチャルリアリティ
gamescamfol1=アクション
gamescamfol2=ホラー
gamescamfol3=リラックス
gamescamfol4=RPG
gamescamfol5=サバイバル
gameslocfol1=Co-op
gameslocfol2=パーティー
gameslocfol3=対戦
gamesonlfol1=大乱戦
gamesonlfol2=MMO
gamesonlfol3=シューティングゲーム
gamesonlfol4=戦略ゲーム

newsmediafol1=左端
newsmediafol2=右端
newsmediafol3=インターナショナル

onlinetools1fol=診断

podcastsfol1=犯罪ドラマ
podcastsfol2=Past & Present
podcastsfol3=政治
podcastsfol4=科学技術
podcastsfol5=セックス＆心理学
podcastsfol6=スポーツ
podcastsfol7=トークショー

bookmarksfol1=ニュース＆メディア
bookmarksfol2=オンラインツール
bookmarksfol3=ポッドキャスト
bookmarksfol4=ショッピング
bookmarks2=Gmail
bookmarks3=Google Keep
bookmarks4=Google Maps
bookmarks5=Google Photos
bookmarks6=Disney+
bookmarks7=Netflix
bookmarks8=Reddit
bookmarks9=Steam
bookmarks10=Twitch
bookmarks11=YouTube

advanced1=コマンド・プロンプト
advanced2=デバイスマネージャ
advanced3=ディスククリーンアップ
advanced4=ディスクの管理
advanced5=レジストリエディタ
advanced6=リソースモニタ
advanced7=スタートアップのアプリ
advanced8=記憶域
advanced9=システム構成
advanced10=Windowsファイアウォール
advanced11=Windows PowerShell
advanced12=Windowsサービス

controlfol1=高度なコントロール
control1=デスクトップの背景
control2=ディスプレイの設定
control3=拡大鏡
control4=オンスクリーンキーボード
control5=電源オプション
control6=ごみ箱
control7=セカンドディスプレイの設定
control8=システム情報
control9=タスクマネージャー
control10=プログラムのアンインストール
control11=ユーザーアカウント