gamesfol2=캠페인
gamesfol3=캐주얼
gamesfol4=인디
gamesfol5=로컬 멀티플레이
gamesfol6=온라인 멀티플레이
gamesfol7=시뮬레이션
gamesfol8=스포츠 & 레이싱
gamesfol9=가상 현실
gamescamfol1=액션
gamescamfol2=공포
gamescamfol3=(휴식)힐링
gamescamfol4=롤 플레잉(RPG)
gamescamfol5=생존
gameslocfol1=협동
gameslocfol2=파티
gameslocfol3=대전게임
gamesonlfol1=배틀 로얄
gamesonlfol2=MMO
gamesonlfol3=슈팅
gamesonlfol4=전략

newsmediafol1=극좌[진보]
newsmediafol2=극우[보수]
newsmediafol3=국제

onlinetools1fol=진단

podcastsfol1=범죄 & 극적인 사건
podcastsfol2=Past & Present
podcastsfol3=정치
podcastsfol4=과학 기술
podcastsfol5=성별 및 심리학
podcastsfol6=스포츠
podcastsfol7=토크쇼

bookmarksfol1=뉴스 & 미디어
bookmarksfol2=온라인 도구
bookmarksfol3=팟캐스트
bookmarksfol4=쇼핑
bookmarks2=Gmail
bookmarks3=Google 메모
bookmarks4=Google 지도
bookmarks5=Google 포토
bookmarks6=훌루
bookmarks7=넷플릭스
bookmarks8=레딧
bookmarks9=스팀
bookmarks10=트위치
bookmarks11=유튜브

advanced1=명령 프롬프트
advanced2=디바이스 관리자
advanced3=디스크 정리
advanced4=디스크 관리
advanced5=레지스트리 편집기
advanced6=리소스 모니터
advanced7=시작 앱
advanced8=저장공간
advanced9=시스템 설정
advanced10=Windows 방화벽
advanced11=Windows PowerShell
advanced12=Windows 서비스

controlfol1=고급 컨트롤
control1=데스크탑 바탕화면
control2=디스플레이 설정
control3=확대
control4=화상 키보드
control5=전원 옵션
control6=휴지통
control7=디스플레이 전환
control8=시스템 정보
control9=작업 관리자
control10=프로그램 제거
control11=사용자 계정