gamesfol2=Kampaìa
gamesfol3=Kasuƒls
gamesfol4=Indie
gamesfol5=Lokƒls daudzsp‰l‰tƒjs
gamesfol6=TieÕsaistes daudzsp‰l‰tƒjs
gamesfol7=Simulƒcija
gamesfol8=Sports un sacŒkstes
gamesfol9=Virtuƒlƒ realitƒte
gamescamfol1=Action
gamescamfol2=Horror
gamescamfol3=Atp×tas
gamescamfol4=RPG
gamescamfol5=IzdzŒvoÕana
gameslocfol1=KooperatŒvs
gameslocfol2=BallŒte
gameslocfol3=Versus
gamesonlfol1=Battle Royale
gamesonlfol2=MMO
gamesonlfol3=¾×teris
gamesonlfol4=Strat‰…ija

newsmediafol1=Latvijas ziìas
newsmediafol2=Re…ionƒlƒs ziìas
newsmediafol3=Starptautiskƒs ziìas

onlinetools1fol=Diagnostika

podcastsfol1=Kriminƒls un drƒma
podcastsfol2=Pagƒtne un tagadne
podcastsfol3=Politika
podcastsfol4=Zinƒtne un tehnolo…ija
podcastsfol5=Sekss un psiholo…ija
podcastsfol6=Sports
podcastsfol7=Sarunu raidŒjumi

bookmarksfol1=Ziìas un mediji
bookmarksfol2=TieÕsaistes rŒki
bookmarksfol3=Spotify podkƒsti
bookmarksfol4=Interneta veikali
bookmarks2=Gmail
bookmarks3=Google Keep
bookmarks4=Google Maps
bookmarks5=Google Photos
bookmarks6=Disney+
bookmarks7=Netflix
bookmarks8=Reddit
bookmarks9=Steam
bookmarks10=Twitch
bookmarks11=YouTube

advanced1=Komandu uzvedne
advanced2=IerŒÑu pƒrvaldnieks
advanced3=Diska tŒrŒÕana
advanced4=Disku pƒrvaldŒba
advanced5=Re…istra redaktors
advanced6=Resource monitor
advanced7=Sƒkuma programmas
advanced8=Krƒtuves vietas
advanced9=Sist‰mas konfigurƒcija
advanced10=Windows ugunsm×ris
advanced11=Windows PowerShell
advanced12=Windows services

controlfol1=Papildu vadŒklas
control1=Personaliz‰Õana
control2=Displeja iestatŒjumi
control3=Lupa
control4=Ekrƒntastat×ra
control5=Ener…ijas opcijas
control6=Atkritne
control7=Att‰lojuma opcijas izv‰le
control8=Sist‰mas informƒcija
control9=Uzdevumu pƒrvaldnieks
control10=Instal‰tƒs programmas
control11=Lietotƒju konti