gamesfol2=Een speler
gamesfol3=Gewoontjes
gamesfol4=Onafhankelijk
gamesfol5=Lokale multiplayer
gamesfol6=Online multiplayer
gamesfol7=Simulatie
gamesfol8=Sport en racen
gamesfol9=Virtuele realiteit
gamescamfol1=Actie
gamescamfol2=Verschrikking
gamescamfol3=Ontspannen
gamescamfol4=RPG
gamescamfol5=Overleving
gameslocfol1=Coöperatief
gameslocfol2=Partij
gameslocfol3=Versus
gamesonlfol1=Vecht tegen koninklijk
gamesonlfol2=MMO
gamesonlfol3=Schutter
gamesonlfol4=Strategie

newsmediafol1=Far-Left
newsmediafol2=Far-Right
newsmediafol3=Internationale

onlinetools1fol=Diagnostiek

podcastsfol1=Misdaad & Drama
podcastsfol2=Past & Present
podcastsfol3=Politiek
podcastsfol4=Wetenschap & Technologie
podcastsfol5=Seks & Psychologie
podcastsfol6=Sport
podcastsfol7=Talk shows

bookmarksfol1=Nieuws en media
bookmarksfol2=Online tools
bookmarksfol3=Spotify Podcasts
bookmarksfol4=Shopping
bookmarks2=Gmail
bookmarks3=Google Keep
bookmarks4=Google Maps
bookmarks5=Google Photos
bookmarks6=Disney+
bookmarks7=Netflix
bookmarks8=Reddit
bookmarks9=Steam
bookmarks10=Twitch
bookmarks11=YouTube

advanced1=Commandoprompt
advanced2=Apparaatbeheer
advanced3=Schijf schoonmaak
advanced4=Schijfbeheer
advanced5=Registry beheer
advanced6=Bronnenmonitor
advanced7=Opstart-apps
advanced8=Opslagruimtes
advanced9=Systeemconfiguratie
advanced10=Windows firewall
advanced11=Windows PowerShell
advanced12=Windows services

controlfol1=Geavanceerde opties
control1=Bureaublad achtergrond
control2=Display instellingen
control3=Inzoomen
control4=Scherm-toetsenbord
control5=Energieopties
control6=Prullenbak
control7=Wissel scherm
control8=Systeem informatie
control9=Taak beheer
control10=Programma verwijderen
control11=Gebruikers accounts