gamesfol2=Kampania
gamesfol3=Rekreacyjne
gamesfol4=Niezale¿ne
gamesfol5=Local multiplayer
gamesfol6=Online multiplayer
gamesfol7=Symulacje
gamesfol8=Sportowe i wyœcigowe
gamesfol9=Wirtualna rzeczywistoœæ
gamescamfol1=Akcja
gamescamfol2=Horror
gamescamfol3=Spokojne
gamescamfol4=RPG
gamescamfol5=Surwiwal
gameslocfol1=Kooperacja
gameslocfol2=Impreza
gameslocfol3=Versus
gamesonlfol1=Battle Royale
gamesonlfol2=MMO
gamesonlfol3=Strzelanki
gamesonlfol4=Strategie

newsmediafol1=Skrajnie lewicowe
newsmediafol2=Skrajnie prawicowe
newsmediafol3=Miêdzynarodowe

onlinetools1fol=Diagnostyka

podcastsfol1=Kryminalne i obyczajowe
podcastsfol2=Past & Present
podcastsfol3=Polityka
podcastsfol4=Nauka i Technologia
podcastsfol5=Seks i Psychologia
podcastsfol6=Sport
podcastsfol7=Wywiady

bookmarksfol1=Wiadomoœci i media
bookmarksfol2=Narzêdzia internetowe
bookmarksfol3=Podcasty
bookmarksfol4=Zakupy
bookmarks2=Gmail
bookmarks3=Google Keep
bookmarks4=Google Maps
bookmarks5=Google Photos
bookmarks6=Disney+
bookmarks7=Netflix
bookmarks8=Reddit
bookmarks9=Steam
bookmarks10=Twitch
bookmarks11=YouTube

advanced1=Wiersz poleceñ
advanced2=Menad¿er urz¹dzeñ
advanced3=Czyszczenie dysku
advanced4=Zarz¹dzanie dyskami
advanced5=Edytor rejestru
advanced6=Monitor zasobów
advanced7=Autostart
advanced8=Miejsce na dyskach
advanced9=Konfiguracja systemu
advanced10=Firewall Windows
advanced11=Windows PowerShell
advanced12=Us³ugi Windows

controlfol1=Ustawienia zaawansowane
control1=T³o pulpitu
control2=Ustawienia wyœwietlania
control3=Powiêkszenie
control4=Klawiatura ekranowa
control5=Opcje zasilania
control6=Kosz
control7=Prze³¹cz ekran
control8=Informacje systemowe
control9=Menad¿er zadañ
control10=Odinstaluj program
control11=Zarz¹dzanie kontami