gamesfol2=Jogador individual
gamesfol3=Casual
gamesfol4=Independente
gamesfol5=Multijogador local
gamesfol6=Multijogador online
gamesfol7=Simula‡„o
gamesfol8=Esportes e corrida
gamesfol9=Realidade virtual
gamescamfol1=A‡„o
gamescamfol2=Horror
gamescamfol3=Relaxado
gamescamfol4=RPG
gamescamfol5=Sobrevivˆncia
gameslocfol1=Cooperativo
gameslocfol2=Festa
gameslocfol3=Versus
gamesonlfol1=Batalha real
gamesonlfol2=MMO
gamesonlfol3=Atirador
gamesonlfol4=Estrat‚gia

newsmediafol1=Extrema-esquerda
newsmediafol2=Extrema-direita
newsmediafol3=Internacional

onlinetools1fol=Diagn¢stico

podcastsfol1=Drama e crime
podcastsfol2=Past & Present
podcastsfol3=Pol¡tica
podcastsfol4=Tecnologia e ciˆncia
podcastsfol5=Sexo e Psicologia
podcastsfol6=Esportes
podcastsfol7=Talk Shows

bookmarksfol1=Meios de comunica‡„o
bookmarksfol2=Ferramentas online
bookmarksfol3=Spotify Podcasts
bookmarksfol4=Compras
bookmarks2=Gmail
bookmarks3=Google Keep
bookmarks4=Google Maps
bookmarks5=Google Photos
bookmarks6=Disney+
bookmarks7=Netflix
bookmarks8=Reddit
bookmarks9=Steam
bookmarks10=Twitch
bookmarks11=YouTube

advanced1=Prompt de comando
advanced2=Gerenciador de Dispositivos
advanced3=Limpeza de disco
advanced4=Gerenciamento de Disco
advanced5=Editor de registro
advanced6=Monitor de recursos
advanced7=Aplicativos de inicializa‡„o
advanced8=Espa‡os de armazenamento
advanced9=Configura‡„o do sistema
advanced10=Firewall do Windows
advanced11=Windows PowerShell
advanced12=Servi‡os do Windows

controlfol1=Controles avan‡ados
control1=Papel de parede
control2=Configura‡”es do visor
control3=Ampliar
control4=Teclado na tela
control5=Op‡”es de energia
control6=Lixeira
control7=Mudar exibi‡„o
control8=Informa‡„o do sistema
control9=Gerenciador de tarefas
control10=Desinstalar um programa
control11=Contas de usu rio