gamesfol2=Один игрок
gamesfol3=Повседневная
gamesfol4=Независимый
gamesfol5=Локальный мультиплеер
gamesfol6=Сетевой мультиплеер
gamesfol7=Моделирование
gamesfol8=Спорт и гонки
gamesfol9=Виртуальная реальность
gamescamfol1=Действие
gamescamfol2=Фильм ужасов
gamescamfol3=Расслабленный
gamescamfol4=RPG
gamescamfol5=Выживание
gameslocfol1=Кооператив
gameslocfol2=Партия
gameslocfol3=Против
gamesonlfol1=Королевская битва
gamesonlfol2=MMO
gamesonlfol3=Стрелок
gamesonlfol4=Стратегия

newsmediafol1=Far-Left
newsmediafol2=Far-Right
newsmediafol3=Международный

onlinetools1fol=Диагностика

podcastsfol1=Криминал и Драма
podcastsfol2=Past & Present
podcastsfol3=Политика
podcastsfol4=Наука и Технологии
podcastsfol5=Секс и Психология
podcastsfol6=Спорт
podcastsfol7=Ток-шоу

bookmarksfol1=Новости и СМИ
bookmarksfol2=Онлайн инструменты
bookmarksfol3=Подкасты
bookmarksfol4=Покупки
bookmarks2=Gmail
bookmarks3=Google Keep
bookmarks4=Google Maps
bookmarks5=Google Photos
bookmarks6=Disney+
bookmarks7=Netflix
bookmarks8=Reddit
bookmarks9=Steam
bookmarks10=Twitch
bookmarks11=YouTube

advanced1=Командная строка
advanced2=Диспечер устройств
advanced3=Очистка диска
advanced4=Управление диском
advanced5=Редактор реестра
advanced6=Монитор ресурсов
advanced7=Приложения для запуска
advanced8=Места для хранения
advanced9=Конфигурация системы
advanced10=Брандмауэр Windows
advanced11=Windows PowerShell
advanced12=Службы Windows

controlfol1=Дополнительные настройки
control1=Фон рабочего стола
control2=Настройки экрана
control3=Увеличивать
control4=Экранная клавиатура
control5=Настройки питания
control6=Корзина
control7=Переключить дисплей
control8=Системная информация
control9=Диспечер задач
control10=Удалить программу
control11=Акаунты пользователя