gamesfol2=Campaign
gamesfol3=Casual
gamesfol4=Indie
gamesfol5=Local multiplayer
gamesfol6=Online multiplayer
gamesfol7=Simulation
gamesfol8=Sports & racing
gamesfol9=Virtual Reality
gamescamfol1=Action
gamescamfol2=Horror
gamescamfol3=Relaxed
gamescamfol4=RPG
gamescamfol5=Survival
gameslocfol1=Co-op
gameslocfol2=Party
gameslocfol3=Versus
gamesonlfol1=Battle Royale
gamesonlfol2=MMO
gamesonlfol3=Shooter
gamesonlfol4=Strategy

newsmediafol1=Væavo
newsmediafol2=Vpravo
newsmediafol3=Medzin·rodn˝

onlinetools1fol=Diaknostika

podcastsfol1=Krimi & dr·ma
podcastsfol2=Past & Present
podcastsfol3=Politika
podcastsfol4=Veda a technolÛgia
podcastsfol5=Sex & psycholÛgia
podcastsfol6=äporty
podcastsfol7=DiskusnÈ rel·cie

bookmarksfol1=Spr·vy & mÈdia
bookmarksfol2=Online n·stroje
bookmarksfol3=Podkasty
bookmarksfol4=Nakupovanie
bookmarks2=Gmail
bookmarks3=Google Keep
bookmarks4=Google Maps
bookmarks5=Google Photos
bookmarks6=Disney+
bookmarks7=Netflix
bookmarks8=Reddit
bookmarks9=Steam
bookmarks10=Twitch
bookmarks11=YouTube

advanced1=PrÌkazov˝ riadok
advanced2=Spr·vca zariadenÌ
advanced3=»istenie disku
advanced4=Spr·va diskov
advanced5=Registry editor
advanced6=Resource monitor
advanced7=Aplik·cie pri spustenÌ
advanced8=Ukladacie priestory
advanced9=System configuration
advanced10=Windows firewall
advanced11=Windows PowerShell
advanced12=Sluûby

controlfol1=N·stoje na spr·vu
control1=Pozadie
control2=Nastavenie obrazovky
control3=Zv‰Ëöovacie sklo
control4=Kl·vesnica na obrazovke
control5=Moûnosti nap·jania
control6=KÙö
control7=Premietaù
control8=SystÈmovÈ inform·cie
control9=Spr·vca ˙loh
control10=Aplik·cie a s˙Ëasti
control11=Spravovaù kont·