gamesfol2=Fushata
gamesfol3=Rastesishme
gamesfol4=I pavarur
gamesfol5=Multiplayer lokal
gamesfol6=Multiplayer në internet
gamesfol7=Simulimi
gamesfol8=Sport & gara
gamesfol9=Realitet virtual
gamescamfol1=Veprimi
gamescamfol2=Tmerr
gamescamfol3=Të relaksuar
gamescamfol4=RPG
gamescamfol5=Mbijetesa
gameslocfol1=Co-op
gameslocfol2=Parti
gameslocfol3=Kundër
gamesonlfol1=Battle Royale
gamesonlfol2=MMO
gamesonlfol3=Qitës
gamesonlfol4=Strategjia

newsmediafol1=Far-Left
newsmediafol2=Far-Right
newsmediafol3=ndërkombëtar

onlinetools1fol=Diagnostifiko

podcastsfol1=Krim & drama
podcastsfol2=Past & Present
podcastsfol3=Politikë
podcastsfol4=Shkencë & Teknologji
podcastsfol5=Seks & Psikologji
podcastsfol6=Sporte
podcastsfol7=Bisedë, debat

bookmarksfol1=Lajme & media
bookmarksfol2=Mjete online
bookmarksfol3=Podcast-e
bookmarksfol4=Shopping
bookmarks2=Gmail
bookmarks3=Google Keep
bookmarks4=Google Maps
bookmarks5=Google Photos
bookmarks6=Disney+
bookmarks7=Netflix
bookmarks8=Reddit
bookmarks9=Steam
bookmarks10=Twitch
bookmarks11=YouTube

advanced1=Shtypesi i komandave
advanced2=Menaxheri i pajisjeve
advanced3=Pastruesi i diskut
advanced4=Menaxheri i diskut
advanced5=Editori i regjistrave
advanced6=Vëzhguesi i resurseve
advanced7=Aplikacionet startuese
advanced8=Hapësira ruajtëse
advanced9=Konfigurimi i sistemit
advanced10=Windows firewall
advanced11=Windows PowerShell
advanced12=Windows sherbimet

controlfol1=Kontrollat e avancuara
control1=Prapavija e desktopit
control2=Parametrat e ekranit
control3=Zmadho
control4=Tastiera në-ekran
control5=Opsionet e energjisë
control6=Shporta e mbeturinave
control7=Ndërro ekranin
control8=Informacione sistemi
control9=Menaxheri i detyrave
control10=Fshij programe
control11=Llogaritë e perdoruesve