chcp 1250

@echo off

set gamesfol2="Fushata"
set gamesfol3="Rastesishme"
set gamesfol4="I pavarur"
set gamesfol5="Multiplayer lokal"
set gamesfol6="Multiplayer në internet"
set gamesfol7="Simulimi"
set gamesfol8="Sport & gara"
set gamesfol9="Realitet virtual"
set gamescamfol1="Veprimi"
set gamescamfol2="Tmerr"
set gamescamfol3="Të relaksuar"
set gamescamfol4="RPG"
set gamescamfol5="Mbijetesa"
set gameslocfol1="Co-op"
set gameslocfol2="Parti"
set gameslocfol3="Kundër"
set gamesonlfol1="Battle Royale"
set gamesonlfol2="MMO"
set gamesonlfol3="Qitës"
set gamesonlfol4="Strategjia"

set newsmediafol1="Far-Left"
set newsmediafol2="Far-Right"
set newsmediafol3="ndërkombëtar"

set onlinetools1fol="Diagnostifiko"

set podcastsfol1="Krim & drama"
set podcastsfol2="Past & Present"
set podcastsfol3="Politikë"
set podcastsfol4="Shkencë & Teknologji"
set podcastsfol5="Seks & Psikologji"
set podcastsfol6="Sporte"
set podcastsfol7="Bisedë, debat"

set bookmarksfol1="Lajme & media"
set bookmarksfol2="Mjete online"
set bookmarksfol3="Podcast-e"
set bookmarksfol4="Shopping"
set bookmarks2="Gmail"
set bookmarks3="Google Keep"
set bookmarks4="Google Maps"
set bookmarks5="Google Photos"
set bookmarks6="Disney+"
set bookmarks7="Netflix"
set bookmarks8="Reddit"
set bookmarks9="Steam"
set bookmarks10="Twitch"
set bookmarks11="YouTube"

set advanced1="Shtypesi i komandave"
set advanced2="Menaxheri i pajisjeve"
set advanced3="Pastruesi i diskut"
set advanced4="Menaxheri i diskut"
set advanced5="Editori i regjistrave"
set advanced6="Vëzhguesi i resurseve"
set advanced7="Aplikacionet startuese"
set advanced8="Hapësira ruajtëse"
set advanced9="Konfigurimi i sistemit"
set advanced10="Windows firewall"
set advanced11="Windows PowerShell"
set advanced12="Windows sherbimet"

set controlfol1="Kontrollat e avancuara"
set control1="Prapavija e desktopit"
set control2="Parametrat e ekranit"
set control3="Zmadho"
set control4="Tastiera në-ekran"
set control5="Opsionet e energjisë"
set control6="Shporta e mbeturinave"
set control7="Ndërro ekranin"
set control8="Informacione sistemi"
set control9="Menaxheri i detyrave"
set control10="Fshij programe"
set control11="Llogaritë e perdoruesve"

cd %~dp0

call "RenameShortcuts.bat"