gamesfol2=Сюжетки
gamesfol3=Казуальн?
gamesfol4=?нд?
gamesfol5=Локальний мультиплеєр
gamesfol6=Онлайн мультиплеєр
gamesfol7=Симулятори
gamesfol8=Спорт та гонки
gamesfol9=В?ртуальна реальн?сть
gamescamfol1=Бойовик
gamescamfol2=Жахи
gamescamfol3=Релаксован?
gamescamfol4=RPG
gamescamfol5=Виживання
gameslocfol1=Кооперативн?
gameslocfol2=Командн?
gameslocfol3=Протистояння
gamesonlfol1=Корол?вська битва
gamesonlfol2=MMO
gamesonlfol3=Шутер
gamesonlfol4=Стратег?я

newsmediafol1=Ультрал?в?
newsmediafol2=Ультраправ?
newsmediafol3=М?жнародний

onlinetools1fol=Д?агностичний

podcastsfol1=Крим?нал та драмма
podcastsfol2=Past & Present
podcastsfol3=Пол?тика
podcastsfol4=Наука та технолог?ї
podcastsfol5=Секс та психолог?я
podcastsfol6=Спорт
podcastsfol7=Розмовн? шоу

bookmarksfol1=Новини та мед?а
bookmarksfol2=Online tools
bookmarksfol3=Подкасти Spotify
bookmarksfol4=Шоп?н?
bookmarks2=Gmail
bookmarks3=Google скриня
bookmarks4=Google
bookmarks5=Google Фото
bookmarks6=Д?сней+
bookmarks7=Нетфл?кс
bookmarks8=Редд?т
bookmarks9=Steam
bookmarks10=Тв?ч
bookmarks11=Ютуб

advanced1=Командний рядок
advanced2=Диспетчер пристроїв
advanced3=Очищення диска
advanced4=Керування дисками
advanced5=Редактор реєстру
advanced6=Мон?тор ресурс?в
advanced7=Автозапуск програм
advanced8=Storage spaces
advanced9=Конф?гурац?я системи
advanced10=Брандмауер Windows
advanced11=Windows PowerShell
advanced12=Служби Windows

controlfol1=Просунут? налаштування
control1=Фон робочого столу
control2=Налаштування екрану
control3=Екранна лупа
control4=Екранна клав?атура
control5=Параметри живлення
control6=Кошик
control7=Переключити екран
control8=Про систему
control9=Диспетчер завдань
control10=Видалення програм
control11=Обл?ков? записи