chcp 866

REM @echo off

set gamesfol2="Сюжетки"
set gamesfol3="Казуальн?"
set gamesfol4="?нд?"
set gamesfol5="Локальний мультиплеєр"
set gamesfol6="Онлайн мультиплеєр"
set gamesfol7="Симулятори"
set gamesfol8="Спорт та гонки"
set gamesfol9="В?ртуальна реальн?сть"
set gamescamfol1="Бойовик"
set gamescamfol2="Жахи"
set gamescamfol3="Релаксован?"
set gamescamfol4="RPG"
set gamescamfol5="Виживання"
set gameslocfol1="Кооперативн?"
set gameslocfol2="Командн?"
set gameslocfol3="Протистояння"
set gamesonlfol1="Корол?вська битва"
set gamesonlfol2="MMO"
set gamesonlfol3="Шутер"
set gamesonlfol4="Стратег?я"

set newsmediafol1="Ультрал?в?"
set newsmediafol2="Ультраправ?"
set newsmediafol3="М?жнародний"

set onlinetools1fol="Д?агностичний"

set podcastsfol1="Крим?нал та драмма"
set podcastsfol2="Past & Present"
set podcastsfol3="Пол?тика"
set podcastsfol4="Наука та технолог?ї"
set podcastsfol5="Секс та психолог?я"
set podcastsfol6="Спорт"
set podcastsfol7="Розмовн? шоу"

set bookmarksfol1="Новини та мед?а"
set bookmarksfol2="Online tools"
set bookmarksfol3="Подкасти Spotify"
set bookmarksfol4="Шоп?н?"
set bookmarks2="Gmail"
set bookmarks3="Google скриня"
set bookmarks4="Google"
set bookmarks5="Google Фото"
set bookmarks6="Д?сней+"
set bookmarks7="Нетфл?кс"
set bookmarks8="Редд?т"
set bookmarks9="Steam"
set bookmarks10="Тв?ч"
set bookmarks11="Ютуб"

set advanced1="Командний рядок"
set advanced2="Диспетчер пристроїв"
set advanced3="Очищення диска"
set advanced4="Керування дисками"
set advanced5="Редактор реєстру"
set advanced6="Мон?тор ресурс?в"
set advanced7="Автозапуск програм"
set advanced8="Storage spaces"
set advanced9="Конф?гурац?я системи"
set advanced10="Брандмауер Windows"
set advanced11="Windows PowerShell"
set advanced12="Служби Windows"

set controlfol1="Просунут? налаштування"
set control1="Фон робочого столу"
set control2="Налаштування екрану"
set control3="Екранна лупа"
set control4="Екранна клав?атура"
set control5="Параметри живлення"
set control6="Кошик"
set control7="Переключити екран"
set control8="Про систему"
set control9="Диспетчер завдань"
set control10="Видалення програм"
set control11="Обл?ков? записи"

cd %~dp0

call "RenameShortcuts.bat"