gamesfol2=Chi?n d?ch
gamesfol3=Ðõn thu?n
gamesfol4=Indie
gamesfol5=Nhi?u ngý?i chõi c?c b?
gamesfol6=Nhi?u ngý?i chõi tr?c tuy?n
gamesfol7=Th? nghi?m
gamesfol8=Th? thao & thi ðua
gamesfol9=Th?c t? ?o
gamescamfol1=Hành ð?ng
gamescamfol2=Kinh d?
gamescamfol3=Thý gi?n
gamescamfol4=Tr? nh?p vai
gamescamfol5=Tr? s?ng c?n
gameslocfol1=tr? h?p tác
gameslocfol2=Ti?c
gameslocfol3=Thách ð?u
gamesonlfol1=Chi?n ð?u ð?i h?ng gia
gamesonlfol2=MMO
gamesonlfol3=B?n súng
gamesonlfol4=Chi?n lý?c

newsmediafol1=Xa trái
newsmediafol2=Xa ph?i
newsmediafol3=Qu?c t?

onlinetools1fol=Ch?n ðoán

podcastsfol1=T?i ph?m
podcastsfol2=Past & Present
podcastsfol3=Chính tr?
podcastsfol4=Khoa h?c & công ngh?
podcastsfol5=T?nh d?c & Tâm l?
podcastsfol6=Th? thao
podcastsfol7=Chýõng tr?nh tr? chuy?n

bookmarksfol1=Th?i s? & phýõng ti?n
bookmarksfol2=D?ng c? tr?c tuy?n
bookmarksfol3=Spotify Podcasts
bookmarksfol4=Mua s?m
bookmarks2=Gmail
bookmarks3=Google Keep
bookmarks4=Google Maps
bookmarks5=Google Photos
bookmarks6=Disney+
bookmarks7=Netflix
bookmarks8=Reddit
bookmarks9=Steam
bookmarks10=Twitch
bookmarks11=YouTube

advanced1=D?u nh?c l?nh
advanced2=Qu?n l? thi?t b?
advanced3=D?n d?p ð?a
advanced4=Qu?n l? ð?a
advanced5=Tr?nh ch?nh s?a s? ðãng k?
advanced6=Giám sát tài nguyên
advanced7=?ng d?ng kh?i ð?ng
advanced8=Không gian dung lý?ng
advanced9=Cài ð?t h? th?ng
advanced10=Windows firewall
advanced11=Windows PowerShell
advanced12=D?ch v? Windows

controlfol1=Ði?u ch?nh nâng cao
control1=H?nh n?n
control2=Cài ð?t hi?n th?
control3=Kính lúp
control4=Bàn phím trên màn h?nh
control5=Tùy ch?n ngu?n
control6=Thùng rác tái ch?
control7=Ð?i màn h?nh hi?n th?
control8=Thông tin thi?t b?
control9=Qu?n l? tác v?
control10=G? b? ?ng d?ng
control11=Tài kho?n ngý?i dùng