gamesfol2=活動
gamesfol3=休閒
gamesfol4=遊戲
gamesfol5=本地多人
gamesfol6=線上多人
gamesfol7=模擬
gamesfol8=運動和賽車
gamesfol9=VR (虛擬實境)
gamescamfol1=動作
gamescamfol2=恐怖
gamescamfol3=放鬆
gamescamfol4=RPG
gamescamfol5=生存
gameslocfol1=合作
gameslocfol2=派對
gameslocfol3=對戰
gamesonlfol1=戰鬥
gamesonlfol2=MMO
gamesonlfol3=射擊
gamesonlfol4=策略

newsmediafol1=左方
newsmediafol2=右方
newsmediafol3=國際

onlinetools1fol=診斷

podcastsfol1=罪案與戲劇
podcastsfol2=Past & Present
podcastsfol3=政治
podcastsfol4=科學和科技
podcastsfol5=性和心理學
podcastsfol6=運動
podcastsfol7=談論節目

bookmarksfol1=新聞和媒體
bookmarksfol2=在線工具
bookmarksfol3=電臺
bookmarksfol4=購物
bookmarks2=Gmail
bookmarks3=Google Keep
bookmarks4=Google Maps
bookmarks5=Google Photos
bookmarks6=Disney+
bookmarks7=Netflix
bookmarks8=Reddit
bookmarks9=Steam
bookmarks10=Twitch
bookmarks11=YouTube

advanced1=命令提示符
advanced2=裝置管理員
advanced3=磁碟清理
advanced4=磁碟管理
advanced5=註冊表編輯器
advanced6=資源檢測器
advanced7=自動?動應用程式
advanced8=存儲空間
advanced9=系統配置
advanced10=Windows 防火牆
advanced11=Windows PowerShell
advanced12=Windows 服務

controlfol1=進階控制
control1=桌面背景
control2=顯示設定
control3=放大
control4=軟鍵盤
control5=能量選項
control6=資源回收桶
control7=轉換螢幕
control8=系統資訊
control9=工作管理員
control10=解除安裝
control11=用戶賬戶