[Variables]

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=Recycle_Bin-Phan
MyAppName=Recycle Bin
MyAppAuthor=Phan
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\Recycle_Bin-Phan\Variables\Variables.inc
MyAppGUID=4cdab24f-5a15-45ea-9756-4c425be1f17d

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------
