[Variables]

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=Recycle_Bin-Phan
MyAppGUID=a2b832eb-8937-49a2-b4ab-6e8ce6a63396
MyAppName=Recycle Bin
MyAppAuthor=Phan
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\Recycle_Bin-Phan\Variables\Variables.inc

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------
