[Variables]

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=Recycle_Bin-Phan
MyAppName=Recycle Bin
MyAppAuthor=Phan
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\Recycle_Bin-Phan\Variables\Variables.inc

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------
