rmdir /s /q "%USERPROFILE%\Documents\Rainmeter\Skins\Droptop Folders\Bookmarks"
rmdir /s /q "%USERPROFILE%\Documents\Rainmeter\Skins\Droptop Folders\Control"
rmdir /s /q "%USERPROFILE%\Documents\Rainmeter\Skins\Droptop Folders\CustomFolder1"
rmdir /s /q "%USERPROFILE%\Documents\Rainmeter\Skins\Droptop Folders\CustomFolder2"
rmdir /s /q "%USERPROFILE%\Documents\Rainmeter\Skins\Droptop Folders\CustomFolder3"
rmdir /s /q "%USERPROFILE%\Documents\Rainmeter\Skins\Droptop Folders\CustomFolder4"
rmdir /s /q "%USERPROFILE%\Documents\Rainmeter\Skins\Droptop Folders\CustomFolder5"
rmdir /s /q "%USERPROFILE%\Documents\Rainmeter\Skins\Droptop Folders\CustomFolder6"
rmdir /s /q "%USERPROFILE%\Documents\Rainmeter\Skins\Droptop Folders\CustomFolder7"
rmdir /s /q "%USERPROFILE%\Documents\Rainmeter\Skins\Droptop Folders\Games"
rmdir /s /q "%USERPROFILE%\Documents\Rainmeter\Skins\Droptop Folders\Other files"

xcopy /s /e /y /f /h "%USERPROFILE%\Documents\Rainmeter\Skins\Droptop\@Resources\OriginalFolders" "%USERPROFILE%\Documents\Rainmeter\Skins\Droptop Folders"

REM attrib +s /d /s "%USERPROFILE%\Documents\Rainmeter\Skins\Droptop Folders\Games\*"
REM attrib +h /s "%USERPROFILE%\Documents\Rainmeter\Skins\Droptop Folders\desktop.ini"