[Variables]
; -------------------------------------------------------------------------------
; VariablesData.inc is used to store variables for your app that are not user-specific or user-configurable.
; Variables in this document should be used to control the app's general functionality.
; -------------------------------------------------------------------------------

MyAppVersion=25.0517

UsageMonitor.NetDivisor0=1000000
UsageMonitor.NetDivisor1=1000

UsageMonitorNetLetter0=M
UsageMonitorNetLetter1=K
