[Variables]
; -------------------------------------------------------------------------------
; VariablesDefault.inc should be a copy of Variables.inc, but contain all of the 'default' settings when the app is first installed.
; Any settings changed by the user should be written to Variables.inc, not VariablesDefault.inc.
; VariablesDefault.inc and Variables.inc should contain all of the user-configurable options for your app.
; -------------------------------------------------------------------------------

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=QRes-Cariboudjan
MyAppName=QRes
MyAppAuthor=Cariboudjan
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\QRes-Cariboudjan\Variables\Variables.inc

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------

Qres.Mode1.res=2
Qres.Mode2.res=3
Qres.Mode3.res=7

Qres.Mode1.hz=1
Qres.Mode2.hz=4
Qres.Mode3.hz=1

res1.x=1920
res2.x=1920
res3.x=2560
res4.x=3840
res5.x=7680
res6.x=1366
res7.x=1280

res1.y=1080
res2.y=1200
res3.y=1440
res4.y=2160
res5.y=4320
res6.y=768
res7.y=720

Hz1=60
Hz2=75
Hz3=120
Hz4=144
Hz5=240
MyAppGUID=4f53e714-a2b8-4ef2-9773-234421341ea3
