[Variables]
; -------------------------------------------------------------------------------
; VariablesDefault.inc should contain all or most of the variables required for the app's function, especially user settings.
; VariablesDefault.inc keys and values are the default settings when the app is first installed or reinstalled.
; Any settings changed by the user should be written to Variables.in, not VariablesDefault.inc.
; All keys in Variables.inc supercede the identical keys of VariablesDefault.inc. 
; VariablesDefault.inc acts as a backup and fallback.
; -------------------------------------------------------------------------------

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=Hide_Settings_Menu-TheyCallMePapa
MyAppName=Hide Settings Menu
MyAppAuthor=TheyCallMePapa
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\Hide_Settings_Menu-TheyCallMePapa\Variables\Variables.inc

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------
ShowHideHomeButton=0

ShowHideHomeButtonApp=0
MyAppGUID=c8467315-7a5c-4307-9cfd-d6a5fc70537f
