[Variables]

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=Quick_Settings-Cariboudjan
MyAppName=Quick Settings
MyAppAuthor=Cariboudjan
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\Quick_Settings-Cariboudjan\Variables\Variables.inc

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------

QuickSettings0=["#@#Scripts\DroptopAHK.#AHKType#" "QuickSettings"]
QuickSettings1=[ms-actioncenter:]
QuickSettingsSelect=0
