[Variables]
; -------------------------------------------------------------------------------
; VariablesData.inc is used to store variables for your app that are not user-specific or user-configurable.
; Variables in this document should be used to control the app's general functionality.
; -------------------------------------------------------------------------------

LocationShortcutButton1=#SKINSPATH#Droptop Community Apps\Apps\Shortcut-Phan\Icons\ButtonS1.png
LocationShortcutButton2=#SKINSPATH#Droptop Community Apps\Apps\Shortcut-Phan\Icons\ButtonS2.png
LocationShortcutButton3=#SKINSPATH#Droptop Community Apps\Apps\Shortcut-Phan\Icons\ButtonS3.png
LocationShortcutButton4=#SKINSPATH#Droptop Community Apps\Apps\Shortcut-Phan\Icons\ButtonS4.png
LocationShortcutButton5=#SKINSPATH#Droptop Community Apps\Apps\Shortcut-Phan\Icons\ButtonS5.png

ShortcutButton1=1
ShortcutButton2=2
ShortcutButton3=3
ShortcutButton4=4
ShortcutButton5=5