[Variables]

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=Shortcut-Phan
MyAppName=Shortcut
MyAppAuthor=Phan
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\Shortcut-Phan\Variables\Variables.inc

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------

Shortcut.NumberOfShortcuts=3

PathShortcutButton1=["C:\"]
PathShortcutButton2=["%USERPROFILE%\Documents"]
PathShortcutButton3=
PathShortcutButton4=
PathShortcutButton5=

LocationShortcutButton1=#SKINSPATH#Droptop Community Apps\Apps\Shortcut-Phan\Icons\Button[#TopIconShadows[#TopBarFontShadow][#ChamLum1][#ReverseDarkLight]]1.png
LocationShortcutButton2=#SKINSPATH#Droptop Community Apps\Apps\Shortcut-Phan\Icons\Button[#TopIconShadows[#TopBarFontShadow][#ChamLum1][#ReverseDarkLight]]2.png
LocationShortcutButton3=#SKINSPATH#Droptop Community Apps\Apps\Shortcut-Phan\Icons\Button[#TopIconShadows[#TopBarFontShadow][#ChamLum1][#ReverseDarkLight]]3.png
LocationShortcutButton4=#SKINSPATH#Droptop Community Apps\Apps\Shortcut-Phan\Icons\Button[#TopIconShadows[#TopBarFontShadow][#ChamLum1][#ReverseDarkLight]]4.png
LocationShortcutButton5=#SKINSPATH#Droptop Community Apps\Apps\Shortcut-Phan\Icons\Button[#TopIconShadows[#TopBarFontShadow][#ChamLum1][#ReverseDarkLight]]5.png

ShortcutButton1=1
ShortcutButton2=2
ShortcutButton3=3
ShortcutButton4=4
ShortcutButton5=5

ShortcutButtonCustomAppNum=#Shortcut-Phan#
CurrentShortcut=1
QuickLinkMode=0

Shortcut.Greyscale=0
