[Variables]

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=Shortcut-Phan
MyAppName=Shortcut
MyAppAuthor=Phan
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\Shortcut-Phan\Variables\Variables.inc
MyAppGUID=b09aea21-6371-4fbf-a472-0d5edada8967

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------

Shortcut.IconSize=0.5

Shortcut.Greyscale=0

Shortcut.NumberOfItems=4
Shortcut.AboveTotal=0
