[Variables]

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=Shortcut-Phan
MyAppName=Shortcut
MyAppAuthor=Phan
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\Shortcut-Phan\Variables\Variables.inc

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------

Shortcut.NumberOfShortcuts=5

PathShortcutButton1=["C:\"]
PathShortcutButton2=["C:\Program Files\Meta Quest Remote Desktop\Meta Quest Remote Desktop.exe"]
PathShortcutButton3=["C:\Users\Carib\Videos"]
PathShortcutButton4=["C:\Users\Carib\Desktop\Cyberpunk 2077.url"]
PathShortcutButton5=["C:\Users\Carib\Desktop\Disco Elysium.url"]

ShortcutButtonCustomAppNum=#Shortcut-Phan#
CurrentShortcut=1
QuickLinkMode=0

Shortcut.Greyscale=0
