[Variables]

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=Shortcut-Phan
MyAppName=Shortcut
MyAppAuthor=Phan
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\Shortcut-Phan\Variables\Variables.inc

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------

Shortcut.NumberOfShortcuts=5

PathShortcutButton1=["C:\"]
PathShortcutButton2=["%USERPROFILE%\Documents"]
PathShortcutButton3=
PathShortcutButton4=
PathShortcutButton5=

ShortcutButtonCustomAppNum=#Shortcut-Phan#
CurrentShortcut=1
QuickLinkMode=0

Shortcut.Greyscale=0
MyAppGUID=b09aea21-6371-4fbf-a472-0d5edada8967
