[Variables]
; -------------------------------------------------------------------------------
; VariablesData.inc is used to store variables for your app that are not user-specific.
; Variables in this document will not be preserved by an app update.
; Variables in this document should be used to control the app's general functionality.
; -------------------------------------------------------------------------------

