[Variables]

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=Theme_Me-Mike_Boynton
MyAppName=Theme Me
MyAppAuthor=Mike Boynton
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\Theme_Me-Mike_Boynton\Variables\Variables.inc

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------

SavedThemeName1=Empty theme slot 1 
SavedThemeAuthor1= 
SavedThemeTime1=
SavedThemeColor1=#DropdownFontColor1#
SavedThemeActive1=0

SavedThemeName2=Empty theme slot 2
SavedThemeAuthor2=
SavedThemeTime2=
SavedThemeColor2=#DropdownFontColor1#
SavedThemeActive2=0

SavedThemeName3=Empty theme slot 3
SavedThemeAuthor3=
SavedThemeTime3=
SavedThemeColor3=#DropdownFontColor1#
SavedThemeActive3=0

SavedThemeName4=Empty theme slot 4
SavedThemeAuthor4=
SavedThemeTime4=
SavedThemeColor4=#DropdownFontColor1#
SavedThemeActive4=0

SavedThemeName5=Empty theme slot 5
SavedThemeAuthor5=
SavedThemeTime5=
SavedThemeColor5=#DropdownFontColor1#
SavedThemeActive5=0

SavedThemeName6=Empty theme slot 6
SavedThemeAuthor6=
SavedThemeTime6=
SavedThemeColor6=#DropdownFontColor1#
SavedThemeActive6=0

SavedThemeName7=Empty theme slot 7
SavedThemeAuthor7=
SavedThemeTime7=
SavedThemeColor7=#DropdownFontColor1#
SavedThemeActive7=0

SavedThemeName8=Empty theme slot 8
SavedThemeAuthor8=
SavedThemeTime8=
SavedThemeColor8=#DropdownFontColor1#
SavedThemeActive8=0

OverwriteText=Overwrite "[#SavedThemeName[#*CURRENTSECTION*]]"?

LoadText="Load"
DefaultThemeText=Empty theme slot [#*CURRENTSECTION*]
SavedText="Saved "

ThemeSlotNumber=1

AppName=Theme Me
AppVersion=23.0429
AppCreators=Mike Boynton & Cariboudjan
MaxFontSize=(#DropdownItemFontSize#*0.9)
OnOff=1
hb=4
OnOffText=Hide
InfoOnOffText=Off
NumBoxes=2
RoundTo=1

Skin.Width=(#DropdownMenuWidth#+2-(#DropdownMenuCutout#*2))
Skin.Height=100

varkey=#SKINSPATH#Droptop Community Apps\Apps\Theme_Me-Mike_Boynton\Variables\Variables.inc

PreviousAutoThemeChange=0

ThemeChangeNum=1
AutoChangeTime1=%j
AutoChangeTime2=%H
AutoChangeTime3=%M

CurrentItemX=#DropdownMenuWidth#
CurrentItemY=#DropdownItemHeight#
CurrentBoxX=#DropdownMenuWidth#
CurrentFontSize=#DropdownItemFontSize#

AutoThemeChangeOFF=1

ThemeType=Droptop Theme
CurrentTheme=Cathode Theme
MyAppGUID=de642008-a7ec-49ed-a0c8-e840eedfeb8b
