[Variables]

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=Media_Control-Yaron
MyAppName=Media Control
MyAppAuthor=Yaron
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\Media_Control-Yaron\Variables\Variables.inc

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------

MediaControlSkipXSeconds=15

MediaControlOpacity=100
MediaControlColour=#TopBarFontColor1#

MediaControlBackgroundHeight=1

MediaControlHighlight=222,79,44
