chcp 1252

@echo off

set gamesfol2="Kampagne"
set gamesfol3="Gelegenheitsspiele"
set gamesfol4="Indiespiele"
set gamesfol5="Local multiplayer"
set gamesfol6="Online multiplayer"
set gamesfol7="Simulationsspiele"
set gamesfol8="Sport & Rennspiele"
set gamesfol9="Virtual Reality"
set gamescamfol1="Action"
set gamescamfol2="Horror"
set gamescamfol3="Entspannung"
set gamescamfol4="RPG"
set gamescamfol5="Survival"
set gameslocfol1="Co-op"
set gameslocfol2="Party"
set gameslocfol3="Versus"
set gamesonlfol1="Battle Royale"
set gamesonlfol2="MMO"
set gamesonlfol3="Shooter"
set gamesonlfol4="Strategie"

set newsmediafol1="Ganz links"
set newsmediafol2="Ganz rechts"
set newsmediafol3="International"

set onlinetools1fol="Diagnose"

set podcastsfol1="Krimie & Drama"
set podcastsfol2="Past & Present"
set podcastsfol3="Politik"
set podcastsfol4="Wirtschaft & Technologie"
set podcastsfol5="Sex & Psychologie"
set podcastsfol6="Sport"
set podcastsfol7="Talk shows"

set bookmarksfol1="Neuigkeiten & Media"
set bookmarksfol2="Online tools"
set bookmarksfol3="Spotify Podcasts"
set bookmarksfol4="Shopping"
set bookmarks2="Gmail"
set bookmarks3="Google Keep"
set bookmarks4="Google Maps"
set bookmarks5="Google Photos"
set bookmarks6="Disney+"
set bookmarks7="Netflix"
set bookmarks8="Reddit"
set bookmarks9="Steam"
set bookmarks10="Twitch"
set bookmarks11="YouTube"

set advanced1="Eingabeaufforderung"
set advanced2="Geräte-Manager"
set advanced3="Datenträgerbereinigung"
set advanced4="Festplattenmanagement"
set advanced5="Registry Editor"
set advanced6="Ressourcenmonitor"
set advanced7="Autostart Programme"
set advanced8="Speicherplatz"
set advanced9="System Konfiguration"
set advanced10="Windows Firewall"
set advanced11="Windows PowerShell"
set advanced12="Windows Systemdienst"

set controlfol1="Erweiterte Einstellungen"
set control1="Desktop Hintergrund"
set control2="Bildschirmeinstellungen"
set control3="Vergrößern"
set control4="On-screen Tastatur"
set control5="Powerplan Optionen"
set control6="Papierkorb"
set control7="Display wechseln"
set control8="System Informationen"
set control9="Task Manager"
set control10="Programm deinstallieren"
set control11="Benutzer Accounts"

cd %~dp0

call "RenameShortcuts.bat"