chcp 1252

@echo off

set gamesfol2="Campaña"
set gamesfol3="Casual"
set gamesfol4="Indie"
set gamesfol5="Multijugador local"
set gamesfol6="Multijugador en línea"
set gamesfol7="Simulación"
set gamesfol8="Deportes y carreras"
set gamesfol9="Realidad virtual"
set gamescamfol1="Acción"
set gamescamfol2="Horror"
set gamescamfol3="Relajado"
set gamescamfol4="RPG"
set gamescamfol5="Supervivencia"
set gameslocfol1="Cooperativo"
set gameslocfol2="Fiesta"
set gameslocfol3="Versus"
set gamesonlfol1="Battle royale"
set gamesonlfol2="MMO"
set gamesonlfol3="Disparos"
set gamesonlfol4="Estrategia"

set newsmediafol1="Extremo izquierdo"
set newsmediafol2="Extremo derecho"
set newsmediafol3="Internacional"

set onlinetools1fol="Diagnóstico"

set podcastsfol1="Crimen y drama"
set podcastsfol2="Past & Present"
set podcastsfol3="Política"
set podcastsfol4="Ciencia y Tecnología"
set podcastsfol5="Sexo y Psicología"
set podcastsfol6="Deportes"
set podcastsfol7="Talk Shows"

set bookmarksfol1="Noticias y medios"
set bookmarksfol2="Herramientas en línea"
set bookmarksfol3="Spotify Podcasts"
set bookmarksfol4="Compras"
set bookmarks2="Gmail"
set bookmarks3="Google Keep"
set bookmarks4="Google Maps"
set bookmarks5="Google Photos"
set bookmarks6="Disney+"
set bookmarks7="Netflix"
set bookmarks8="Reddit"
set bookmarks9="Steam"
set bookmarks10="Twitch"
set bookmarks11="YouTube"

set advanced1="Símbolo del sistema"
set advanced2="Admin. de dispositivos"
set advanced3="Limpieza de disco"
set advanced4="Administración de discos"
set advanced5="Editor del registro"
set advanced6="Monitor de recursos"
set advanced7="Apps de arranque"
set advanced8="Espacios de almac."
set advanced9="Config. del sistema"
set advanced10="Firewall de Windows"
set advanced11="Windows PowerShell"
set advanced12="Servicios de Windows"

set controlfol1="Controles avanzados"
set control1="Fondo de escritorio"
set control2="Conf. de pantalla"
set control3="Lupa"
set control4="Teclado en pantalla"
set control5="Opciones de poder"
set control6="Papelera de reciclaje"
set control7="Cambiar pantalla"
set control8="Info. del sistema"
set control9="Admin. de tareas"
set control10="Desinstalar un programa"
set control11="Usuarios"

cd %~dp0

call "RenameShortcuts.bat"