chcp 1252

@echo off

set gamesfol2="Campagna"
set gamesfol3="Casual"
set gamesfol4="Indie"
set gamesfol5="Multiplayer Locali"
set gamesfol6="Multiplayer Online"
set gamesfol7="Simulazione"
set gamesfol8="Sport & Corse"
set gamesfol9="Realtà Virtuale"
set gamescamfol1="Azione"
set gamescamfol2="Horror"
set gamescamfol3="Rilassanti"
set gamescamfol4="RPG"
set gamescamfol5="Sopravvivenza"
set gameslocfol1="Co-op"
set gameslocfol2="Party"
set gameslocfol3="Versus"
set gamesonlfol1="Battle Royale"
set gamesonlfol2="MMO"
set gamesonlfol3="Sparatutto"
set gamesonlfol4="Strategia"

set newsmediafol1="Di Sinistra"
set newsmediafol2="Di Destra"
set newsmediafol3="Internazionale"

set onlinetools1fol="Diagnostica"

set podcastsfol1="Crime & Dramma"
set podcastsfol2="Past & Present"
set podcastsfol3="Politica"
set podcastsfol4="Scienza & Tecnologia"
set podcastsfol5="Sesso & Psicologia"
set podcastsfol6="Sport"
set podcastsfol7="Talk Show"

set bookmarksfol1="Notizie & Media"
set bookmarksfol2="Strumenti Online"
set bookmarksfol3="Podcast"
set bookmarksfol4="Shopping"
set bookmarks2="Gmail"
set bookmarks3="Google Keep"
set bookmarks4="Google Maps"
set bookmarks5="Google Photos"
set bookmarks6="Disney+"
set bookmarks7="Netflix"
set bookmarks8="Reddit"
set bookmarks9="Steam"
set bookmarks10="Twitch"
set bookmarks11="YouTube"

set advanced1="Prompt dei Comandi"
set advanced2="Gestore Dispositivi"
set advanced3="Pulizia del Disco"
set advanced4="Gestore dei Dischi"
set advanced5="Editor del Registro"
set advanced6="Monitor delle Risorse"
set advanced7="App all'Avvio"
set advanced8="Spazi di Archiviazione"
set advanced9="Configurazione di Sistema"
set advanced10="Firewall di Windows"
set advanced11="Powershell di Windows"
set advanced12="Servizi di Windows"

set controlfol1="Controlli avanzati"
set control1="Sfondi Desktop"
set control2="Impostazioni Display"
set control3="Ingrandisci"
set control4="Tastiera sullo schermo"
set control5="Opzioni di alimentazione"
set control6="Cestino"
set control7="Cambia display"
set control8="Informazioni di Sistema"
set control9="Task Manager"
set control10="Disinstalla un programma"
set control11="Account Utente"

cd %~dp0

call "RenameShortcuts.bat"