chcp 860

@echo off

set gamesfol2="Jogador individual"
set gamesfol3="Casual"
set gamesfol4="Independente"
set gamesfol5="Multijogador local"
set gamesfol6="Multijogador online"
set gamesfol7="Simula‡„o"
set gamesfol8="Esportes e corrida"
set gamesfol9="Realidade virtual"
set gamescamfol1="A‡„o"
set gamescamfol2="Horror"
set gamescamfol3="Relaxado"
set gamescamfol4="RPG"
set gamescamfol5="Sobrevivˆncia"
set gameslocfol1="Cooperativo"
set gameslocfol2="Festa"
set gameslocfol3="Versus"
set gamesonlfol1="Batalha real"
set gamesonlfol2="MMO"
set gamesonlfol3="Atirador"
set gamesonlfol4="Estrat‚gia"

set newsmediafol1="Extrema-esquerda"
set newsmediafol2="Extrema-direita"
set newsmediafol3="Internacional"

set onlinetools1fol="Diagn¢stico"

set podcastsfol1="Drama e crime"
set podcastsfol2="Past & Present"
set podcastsfol3="Pol¡tica"
set podcastsfol4="Tecnologia e ciˆncia"
set podcastsfol5="Sexo e Psicologia"
set podcastsfol6="Esportes"
set podcastsfol7="Talk Shows"

set bookmarksfol1="Meios de comunica‡„o"
set bookmarksfol2="Ferramentas online"
set bookmarksfol3="Spotify Podcasts"
set bookmarksfol4="Compras"
set bookmarks2="Gmail"
set bookmarks3="Google Keep"
set bookmarks4="Google Maps"
set bookmarks5="Google Photos"
set bookmarks6="Disney+"
set bookmarks7="Netflix"
set bookmarks8="Reddit"
set bookmarks9="Steam"
set bookmarks10="Twitch"
set bookmarks11="YouTube"

set advanced1="Prompt de comando"
set advanced2="Gerenciador de Dispositivos"
set advanced3="Limpeza de disco"
set advanced4="Gerenciamento de Disco"
set advanced5="Editor de registro"
set advanced6="Monitor de recursos"
set advanced7="Aplicativos de inicializa‡„o"
set advanced8="Espa‡os de armazenamento"
set advanced9="Configura‡„o do sistema"
set advanced10="Firewall do Windows"
set advanced11="Windows PowerShell"
set advanced12="Servi‡os do Windows"

set controlfol1="Controles avan‡ados"
set control1="Papel de parede"
set control2="Configura‡”es do visor"
set control3="Ampliar"
set control4="Teclado na tela"
set control5="Op‡”es de energia"
set control6="Lixeira"
set control7="Mudar exibi‡„o"
set control8="Informa‡„o do sistema"
set control9="Gerenciador de tarefas"
set control10="Desinstalar um programa"
set control11="Contas de usu rio"

cd %~dp0

call "RenameShortcuts.bat"