REM "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned" required to create RMSKIN files.

set startTime=%time%

git config --global http.sslVerify false

cd "%USERPROFILE%\Documents\GitHub"
git clone https://github.com/Droptop-Four/Beta-Update.git --depth 1  --branch main 
cd "%USERPROFILE%\Documents\GitHub\Beta-Update"
git fetch
git pull

cd "%USERPROFILE%\Documents\GitHub"
git clone https://github.com/Droptop-Four/Droptop-Four.git --depth 1  --branch main 
cd "%USERPROFILE%\Documents\GitHub\Droptop-Four"
git fetch
git pull

cd "%USERPROFILE%\Documents\GitHub"
git clone https://github.com/Droptop-Four/Community-Apps.git --depth 1  --branch main 
cd "%USERPROFILE%\Documents\GitHub\Community-Apps"
git fetch
git pull

cd "C:\"

@echo Reseting configurations to default
TIMEOUT 5

del /f %5Droptop\@Resources\GlobalVar\Languages\ca-ES.inc"
del /f %5Droptop\@Resources\GlobalVar\Languages\ro-RO.inc"
del /f %5Droptop\@Resources\GlobalVar\Languages\th-TH.inc"
del /f %5Droptop\@Resources\GlobalVar\Languages\zh-TW.inc"

attrib -h /s %5Droptop\@Resources\OriginalFolders\desktop.ini"
attrib -s /d /s %5Droptop\@Resources\OriginalFolders\Games\*"
"C:\Program Files\AutoHotkey\Compiler\Ahk2Exe.exe" /in "%USERPROFILE%\Documents\Rainmeter\Skins\Droptop\@Resources\Scripts\DroptopAHK.ahk" /out "%USERPROFILE%\Documents\Rainmeter\Skins\Droptop\@Resources\Scripts\DroptopAHK.exe"
%4 !DeactivateConfigGroup DroptopSuite
%4 !DeactivateConfig Droptop\DropdownBar\AppBar
%4 !WriteKeyValue Variables DroptopIsBeta 0 %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables DroptopIsUpdate 0 %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables Supporter 0 %5Droptop\@Resources\GlobalVar\Supporter.inc"
%4 !WriteKeyValue Variables FolderLoc1 "#SKINSPATH#Droptop Folders\PinnedApps" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderLoc2 "#SKINSPATH#Droptop Folders\Games" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderLoc3 "#SKINSPATH#Droptop Folders\Bookmarks" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderLoc4 "#SKINSPATH#Droptop Folders\Control" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderLoc6 "#SKINSPATH#Droptop Folders\CustomFolder1" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderLoc7 "#SKINSPATH#Droptop Folders\CustomFolder2" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderLoc8 "#SKINSPATH#Droptop Folders\CustomFolder3" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderLoc9 "#SKINSPATH#Droptop Folders\CustomFolder4" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderLoc10 "#SKINSPATH#Droptop Folders\CustomFolder5" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderLoc11 "#SKINSPATH#Droptop Folders\CustomFolder6" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderLoc12 "#SKINSPATH#Droptop Folders\CustomFolder7" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomAppID1 "Droptop_Store-Bunz" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomAppID2 "YouTube-Cariboudjan" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomAppID3 "Messenger-Cariboudjan" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomAppID4 "Usage_Monitor-Cariboudjan" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomAppID5 "Daily_Quotes-Bunz" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomAppID6 "Recycle_Bin-Phan" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomAppID7 "Notepad-Cariboudjan" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomAppID8 "Disks-Phan" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomAppID9 "Google_Gemini-Cariboudjan" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomAppID10 "Functions-Cariboudjan" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomAppInstallDate1 %3" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomAppInstallDate2 %3" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomAppInstallDate3 %3" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomAppInstallDate4 %3" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomAppInstallDate5 %3" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomAppInstallDate6 %3" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomAppInstallDate7 %3" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomAppInstallDate8 %3" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomAppInstallDate9 %3" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomAppInstallDate10 %3" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables Droptop_Store-Bunz 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables Messenger-Cariboudjan 3 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables YouTube-Cariboudjan 2 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables Usage_Monitor-Cariboudjan 4 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables Daily_Quotes-Bunz 5 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables Recycle_Bin-Phan 6 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables Notepad-Cariboudjan 7 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables Disks-Phan 8 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables Google_Gemini-Cariboudjan 9 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables Functions-Cariboudjan 10 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables ReverseDarkLight 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables RecentFileFilter "." %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables RecentFileTypeNum 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables NowPlayingClipNum 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables GmailUsername "" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables GmailPassword "" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables DeviceIsMobile 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables DisplayIsLandscape 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables AlarmHour 9 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables AlarmMinute 30 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables AlarmNum 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables AlarmOFF 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables PomoNum 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables ActionTimer.StartAnimation.Steps 16 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables ActionTimer.StartAnimation.StepsNum 3 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables AutoAltHome 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables AltTitleNum 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables ShowSeconds 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables ShowSecondsBar 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables SetColorByWallpaperOFF 0 %5Droptop\@Resources\Themes\1Settings.inc"
%4 !WriteKeyValue Variables SetColorByWallpaperOFF 0 %5Droptop\@Resources\Themes\2Settings.inc"
%4 !WriteKeyValue Variables SetColorByWallpaperOFF 0 %5Droptop\@Resources\Themes\3Settings.inc"
%4 !WriteKeyValue Variables SetColorByWallpaperOFF 0 %5Droptop\@Resources\Themes\4Settings.inc"
%4 !WriteKeyValue Variables TopBarSections 0 %5Droptop\@Resources\Themes\1Settings.inc"
%4 !WriteKeyValue Variables TopBarSections 1 %5Droptop\@Resources\Themes\2Settings.inc"
%4 !WriteKeyValue Variables TopBarSections 0 %5Droptop\@Resources\Themes\3Settings.inc"
%4 !WriteKeyValue Variables TopBarSections 0 %5Droptop\@Resources\Themes\4Settings.inc"
%4 !WriteKeyValue Variables TopBarBlur 1 %5Droptop\@Resources\Themes\1Settings.inc"
%4 !WriteKeyValue Variables TopBarBlur 0 %5Droptop\@Resources\Themes\2Settings.inc"
%4 !WriteKeyValue Variables TopBarBlur 1 %5Droptop\@Resources\Themes\3Settings.inc"
%4 !WriteKeyValue Variables TopBarBlur 0 %5Droptop\@Resources\Themes\4Settings.inc"
%4 !WriteKeyValue Variables TopBarGradient 0 %5Droptop\@Resources\Themes\1Settings.inc"
%4 !WriteKeyValue Variables TopBarGradient 0 %5Droptop\@Resources\Themes\2Settings.inc"
%4 !WriteKeyValue Variables TopBarGradient 0 %5Droptop\@Resources\Themes\3Settings.inc"
%4 !WriteKeyValue Variables TopBarGradient 0 %5Droptop\@Resources\Themes\4Settings.inc"
%4 !WriteKeyValue Variables HideSupport 0 %5Droptop\Other\Settings\Settings.ini"
%4 !WriteKeyValue Variables UnitsMetric 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables HideWeatherSymbol 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables HideWeatherTemp 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables HideIcons 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderMouseOverTimeNum 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables HomeColumn 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables HomeRow 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomHomeButton 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables HomeColorNum 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderColorNum1 "1" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderColorNum2 "1" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderColorNum3 "1" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderColorNum4 "1" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderColorNum5 "1" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderColorNum6 "1" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderColorNum7 "1" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderColorNum8 "1" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderColorNum9 "1" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderColorNum10 "1" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderColorNum11 "1" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderColorNum12 "1" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsSymbol1 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsSymbol2 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsSymbol3 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsSymbol4 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsSymbol5 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsSymbol6 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsSymbol7 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsSymbol8 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsSymbol9 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsSymbol10 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsSymbol11 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsSymbol12 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsColor1 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsColor2 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsColor3 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsColor4 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsColor5 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsColor6 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsColor7 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsColor8 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsColor9 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsColor10 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsColor11 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderIsColor12 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables HideHomeIcon 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables MailNum 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables MailLink1 """""" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables MailAuthor1 """""" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables MailSubject1 """""" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables MailLink2 """""" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables MailAuthor2 """""" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables MailSubject2 """""" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables MailLink3 """""" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables MailAuthor3 """""" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables MailSubject3 """""" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables MailLink4 """""" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables MailAuthor4 """""" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables MailSubject4 """""" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables UpdateAvailable 0 %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables UpdateCheckFrequency 2 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CrashDetected 0 %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables AppCommandCount 1 %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables Page 0 %5Droptop\Other\Startup\Start.ini"
%4 !WriteKeyValue Variables HomeColorNum 1 %5Droptop\Other\Startup\Start.ini"
%4 !WriteKeyValue Variables IconsSymbolNum 0 %5Droptop\Other\Startup\Start.ini"
%4 !WriteKeyValue Variables TopBarSectionsNum 0 %5Droptop\Other\Startup\Start.ini"
%4 !WriteKeyValue Variables NoAnimationNum 0 %5Droptop\Other\Startup\Style.inc"
%4 !WriteKeyValue Variables HideExtraButtonsVolume 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables DroptopSizeNum 5 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables IconSize Medium %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables TopIconSize Medium %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables TopIconWH 32 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables IconW 32 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables IconH 32 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables DPIOverride 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables DPIRescaleOFF 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CurrentDesktopNum 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables PreviousDesktopTotal 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables AutohideDelayNum 3 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables AutohideSpeedNum 2 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables AutohideTriggerType 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables ShowFolderOverflow 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables DisableAllNotifications 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables PlayerNum 6 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables PlayerTypeNum 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables AlbumMaskNum 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables AlbumBlurGreyscale 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables AlbumBlurTint "215,215,215" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables PlayerTitle0 "" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables PlayerArtist0 "" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables PlayerTitle1 "" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables PlayerArtist1 "" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables PlayerTitle2 "" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables PlayerArtist2 "" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables WebNowPlayingAlbumImage "" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables WebNowPlayingAlbumImage "" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables WebNowPlayingAlbumImage "" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables AlwaysShowSongTitleOFF 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables NowPlayingCustomColor 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables NowPlayingColor "255,255,255" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables NowPlayingOpacity 255 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables HideTimeCenter 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables LanguageNum 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables ThemeNum 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatterySaverON 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryPowerLowThreshold0 20 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryPowerLowThresholdNum 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables Time24HourNum 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables TimeFormatTypeNum 2 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CenterTimeFormatTypeNum 3 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables DroptopDisplayNum 99 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables DroptopPriorityList "Not set" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BacklightCompatibilityMode 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables IPAddress "N/A" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables WNPTooltipDismissed 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables SysIconSizeNum 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables LegacyAppDrawer 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables SlotFolder1 1 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SlotFolder2 2 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SlotFolder3 3 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SlotFolder4 4 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SlotFolder5 5 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SlotFolder6 6 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SlotFolder7 7 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SlotFolder8 8 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SlotFolder9 9 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SlotFolder10 10 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SlotFolder11 11 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SlotFolder12 12 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName1 #SideAppName22# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName2 #SideAppName2# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName3 #SideAppName21# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName4 #SideAppName1# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName5 #SideAppName13# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName6 #SideAppName6# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName7 #SideAppName7# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName8 #SideAppName8# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName9 #SideAppName14# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName10 #SideAppName15# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName11 #SideAppName11# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName12 #SideAppName12# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName13 #SideAppName5# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName14 #SideAppName9# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName15 #SideAppName10# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName16 #SideAppName16# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName17 #SideAppName17# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName18 #SideAppName18# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName19 #SideAppName19# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName20 #SideAppName20# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName21 #SideAppName3# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlotName22 #SideAppName4# %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot1 22 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot2 2 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot3 21 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot4 1 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot5 13 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot6 6 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot7 7 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot8 8 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot9 14 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot10 15 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot11 11 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot12 12 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot13 5 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot14 9 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot15 10 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot16 16 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot17 17 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot18 18 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot19 19 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot20 20 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot21 3 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppSlot22 4 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosNewDesktop 4 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosTime 2 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosAlarm 21 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosVolume 22 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosMail 13 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosWeather 6 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosBattery 7 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosWifi 8 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosDownloads 14 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosRecent 15 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosCopy 11 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosAppDrawer 12 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosCustomApp1 5 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosCustomApp2 9 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosCustomApp3 10 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosCustomApp4 16 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosCustomApp5 17 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosCustomApp6 18 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosCustomApp7 19 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosCustomApp8 20 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosCustomApp9 3 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables SideAppPosCustomApp10 1 %5Droptop\@Resources\GlobalVar\TopBarPos.inc"
%4 !WriteKeyValue Variables FolderHidden1 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables FolderHidden2 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables FolderHidden3 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables FolderHidden4 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables FolderHidden5 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables FolderHidden6 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables FolderHidden7 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables FolderHidden8 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables FolderHidden9 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables FolderHidden10 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables FolderHidden11 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables FolderHidden12 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppNewDesktop 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppTime 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppMail 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppAlarm 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppVolume 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppWeather 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppWifi 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppBattery 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppDownloads 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppRecent 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppCopy 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppAppDrawer 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppCustomApp1 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppCustomApp2 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppCustomApp3 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppCustomApp4 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppCustomApp5 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppCustomApp6 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppCustomApp7 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppCustomApp8 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppCustomApp9 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideAppCustomApp10 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowNewDesktop 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowTime 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowMail 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowAlarm 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowVolume 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowWeather 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowWifi 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowBattery 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowDownloads 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowRecent 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowCopy 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowAppDrawer 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowCustomApp1 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowCustomApp2 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowCustomApp3 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowCustomApp4 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowCustomApp5 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowCustomApp6 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowCustomApp7 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowCustomApp8 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowCustomApp9 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables IsOverflowCustomApp10 0 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider1 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider2 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider3 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider4 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider5 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider6 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider7 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider8 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider9 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider10 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider11 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider12 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider13 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider14 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider15 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider16 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider17 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider18 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider19 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider20 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider21 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables HideTopBarDivider22 1 %5Droptop\@Resources\GlobalVar\FolderSettings.inc"
%4 !WriteKeyValue Variables CustomApp1UpdateAvailable 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomApp2UpdateAvailable 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomApp3UpdateAvailable 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomApp4UpdateAvailable 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomApp5UpdateAvailable 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomApp6UpdateAvailable 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomApp7UpdateAvailable 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomApp8UpdateAvailable 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomApp9UpdateAvailable 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables CustomApp10UpdateAvailable 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables DeviceIsNotTouch 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables ShowBacklightBar 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables AltHome 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables LeftHotCornerActionNum 3 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables RightHotCornerActionNum 2 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables DroptopSleepMode 0 %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables DroptopSleepMinutes 5 %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables AutomaticWeatherLoc 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables ShowBlackCorners 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables HideWinButton 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables HideProgramsApp 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables HideAppCommands 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables HideMailCount 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables HideGmailPreviews 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables AHKNum 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BarXposOffsetNum 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FontSizeOffsetNum 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FontYposOffsetNum 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables DebugModeOFF 1 %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables TopBarWidth "#SCREENAREAWIDTH#" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables LocationLatitude "" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables LocationLongitude "" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables MyLocation "" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables PreviousClipboard "" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables NumberOfItems 1 %5Droptop\Other\Apps\Downloads\Downloads.ini"
%4 !WriteKeyValue Variables NumberOfItems 1 %5Droptop\Other\Apps\Recent\Recent.ini"
%4 !WriteKeyValue Variables EnableDragDrop 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables LargeHomeButton 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables ZposFocused 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables DisableDPINum 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables DPIRescaleValue 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables PopupInFullscreen 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderTitle1 "#FolderName1#" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderTitle2 "#FolderName2#" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderTitle3 "#FolderName3#" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderTitle4 "#FolderName4#" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderTitle5 "#FolderName5#" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderTitle6 "#FolderName6#" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderTitle7 "#FolderName7#" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderTitle8 "#FolderName8#" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderTitle9 "#FolderName9#" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderTitle10 "#FolderName10#" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderTitle11 "#FolderName11#" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables FolderTitle12 "#FolderName12#" %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables LastFocusedApp "Explorer" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables LastFocusedIM "Explorer.EXE" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables LastFocusedTitle "" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables ProcessPath "C:\WINDOWS\Explorer.EXE" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables ProcessLoc "C:\WINDOWS\" %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables ForceOpaque 0 %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables ForceOpaqueON 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables RegionNum "1" %5Droptop\Other\WindowMenu\ThemeBuilder.Create.ini"
%4 !WriteKeyValue Variables CategoryNum "1" %5Droptop\Other\WindowMenu\ThemeBuilder.Create.ini"
%4 !WriteKeyValue Variables SubCatNum "1" %5Droptop\Other\WindowMenu\ThemeBuilder.Create.ini"
%4 !WriteKeyValue Variables VarNum "1" %5Droptop\Other\WindowMenu\ThemeBuilder.Create.ini"
%4 !WriteKeyValue Variables BatteryHourLevel00 40 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel01 60 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel02 80 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel03 100 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel04 100 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel05 80 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel06 60 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel07 40 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel08 20 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel09 20 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel10 40 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel11 60 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel12 80 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel13 100 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel14 100 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel15 80 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel16 60 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel17 40 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel18 20 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel19 20 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel20 40 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel21 60 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel22 80 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryHourLevel23 100 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting00 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting01 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting02 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting03 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting04 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting05 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting06 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting07 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting08 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting09 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting10 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting11 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting12 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting13 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting14 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting15 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting16 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting17 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting18 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting19 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting20 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting21 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting22 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables BatteryReporting23 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
xcopy /y /c /h /e %5Droptop Community Apps\Apps\Sample_App-Cariboudjan" %5Droptop\@Resources\Scripts\AppBuilder\Sample Apps\Sample_App-Cariboudjan"
xcopy /y /c /h /e %5Droptop Community Apps\Apps\Sample_WebView-Cariboudjan" %5Droptop\@Resources\Scripts\AppBuilder\Sample Apps\Sample_WebView-Cariboudjan"
attrib +h /s "%USERPROFILE%\Documents\GitHub\Community-Apps\.gitattributes"
xcopy /y /c /h /e %5Droptop Community Apps\Apps\*" "%USERPROFILE%\Documents\GitHub\Community-Apps"
del /f /q %5Droptop\@Resources\Images\Media\Cover.png"
del /f /q %5Droptop\@Resources\Images\Media\CoverBlur.png"
call %5Droptop\@Resources\Scripts\RestoreFolders.bat" %5
reg add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" /v "C:\Program Files\Rainmeter\Rainmeter.exe" /t "REG_SZ" /d "~ HIGHDPIAWARE" /f
cd %5Droptop\@Resources\Scripts\ImageMagick" & convert %5Droptop\Other\WindowMenu\WallpaperCache\Wallpaper0.png" "Wallpaper1.png" & convert %5Droptop\Other\WindowMenu\WallpaperCache\Wallpaper0.png" -crop 9999x200+0+0 "WallpaperCropped.png" & convert "WallpaperCropped.png" -blur 0x3 "Wallpaper1.0.png" & convert "WallpaperCropped.png" -blur 0x8 "Wallpaper1.1.png" & del /f /q "WallpaperCropped.png" & xcopy /E /I /Y "Wallpaper*.png" %5Droptop\Other\WindowMenu\WallpaperCache" & xcopy /E /I /Y "Wallpaper*.png" %5Droptop Folders\Other files\Themes" & del /f /q "*.png" & taskkill /f /im "convert.exe" & taskkill /f /im "mogrify.exe"
cd %5Droptop\@Resources\Scripts\Other"
REM xcopy /s /e /y /f /i %5Droptop" %5Redistributables\Droptop-Master"
@echo Creating Basic, Update, and Supporter versions...
TIMEOUT 10
del /f /q %5Droptop Folders\Other files\Themes\*.ttf"
del /f /q %5Droptop Folders\Other files\Themes\*.otf"
REM del /f /q %5Droptop Folders\Other files\Themes\Wallpaper1.*"
del /f /q %5Droptop\@Resources\Scripts\AppBuilder\@Rmskins\Droptop Apps\*"
del /f /q %5Droptop\@Resources\Scripts\AppBuilder\@Rmskins\Droptop Themes\*"
%4 !WriteKeyValue Variables FirstLoad 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
RD /S /Q %5Redistributables\Basic-Version\Skins\Droptop"
RD /S /Q %5Redistributables\Basic-Version\Skins\Droptop Community Apps"
xcopy /e /y /f /i %5Droptop\@Resources\Scripts\Other\Layouts\*" %5Redistributables\Basic-Version\Layouts"
xcopy /e /y /f /i %5Droptop\@Resources\Scripts\Other\Layouts\*" %5Redistributables\Update\Layouts"
xcopy /e /y /f /i %5Droptop\@Resources\Scripts\Other\Plugins\*" %5Redistributables\Basic-Version\Plugins"
xcopy /e /y /f /i %5Droptop\@Resources\Scripts\Other\Plugins\*" %5Redistributables\Update\Plugins"
xcopy /e /y /f /i %5Droptop\@Resources\Scripts\Other\Plugins\*" %5Redistributables\Beta-Update\Plugins"
xcopy /e /y /f /i %5Droptop\@Resources\Scripts\AppBuilder\TemplateBackup\*" %5Droptop\@Resources\Scripts\AppBuilder"
xcopy /e /i /y %5Droptop Community Apps" %5Redistributables\Basic-Version\Skins\Droptop Community Apps" /EXCLUDE:XcopyExclude.txt
robocopy %5Droptop" %5Redistributables\Basic-Version\Skins\Droptop" /E
robocopy %5Droptop\@Resources\OriginalFolders" %5Redistributables\Basic-Version\Skins\Droptop Folders" /E
REM "Wscript.exe" %5Droptop\@Resources\Scripts\IconsColor1.vbs" %5"
RD /S /Q %5Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder12"
RD /S /Q %5Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder11"
RD /S /Q %5Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder10"
RD /S /Q %5Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder9"
RD /S /Q %5Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder8"
RD /S /Q %5Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder7"
del /f /q %5Redistributables\Basic-Version\Skins\Droptop Folders\PinnedApps\*"
@echo Basic Version Complete
%4 !WriteKeyValue Variables FirstLoad 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables Supporter 1 %5Droptop\@Resources\GlobalVar\Supporter.inc"
%4 !WriteKeyValue Variables Page 99 %5Droptop\Other\Startup\Start.ini"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop Community Apps"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop Folders"
robocopy %5Droptop" %5Redistributables\Supporter-Version\Skins\Droptop" /E
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\Icons"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\OriginalFolders"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder01"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder02"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder1"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder2"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder3"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder4"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder5"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder6"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\Other\Experiments"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\Other\WindowMenu"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\DropdownBar"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\Folders"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\Other\PowerMenu"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\Other\SettingsMenu"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\Other\Apps"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\Other\Tutorial\Tooltip"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\Other\Tutorial"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\Fonts"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\Images"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\Meters"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\Scripts"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\Sounds"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\Symbols"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\Calendars"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Alarm"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Battery"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Copy"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Downloads"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\AppDrawer"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Mail"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Recent"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Volume"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Weather"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Wifi"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Desktops"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Update"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\Languages"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\Other\BackgroundProcesses"
RD /S /Q %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\Themes"
del /f %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\Control.inc"
del /f %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\IncludedCommands.inc"
del /f %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\FolderSettings.inc"
del /f %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\TopBarPos.inc"
del /f %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\UserSettings.inc"
del /f %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\SettingsMenuOptions.inc"
del /f %5Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\ThemeBuilderOptions.inc"
@echo Supporter Version Complete
%4 !WriteKeyValue Variables FirstLoad 0 %5Droptop\@Resources\GlobalVar\UserSettings.inc"
%4 !WriteKeyValue Variables Supporter 0 %5Droptop\@Resources\GlobalVar\Supporter.inc"
%4 !WriteKeyValue Variables Page 100 %5Droptop\Other\Startup\Start.ini"
%4 !WriteKeyValue Variables DroptopIsUpdate 1 %5Droptop\@Resources\GlobalVar\Control.inc"
RD /S /Q %5Redistributables\Update\Skins\Droptop"
robocopy %5Droptop" %5Redistributables\Update\Skins\Droptop" /E
@echo Update Version Complete
RD /S /Q %5Redistributables\Beta-Update\Skins\Droptop"
robocopy %5Droptop" %5Redistributables\Beta-Update\Skins\Droptop" /E
%4 !WriteKeyValue Variables DroptopIsBeta 1 %5Redistributables\Beta-Update\Skins\Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables DroptopIsUpdate 1 %5Redistributables\Beta-Update\Skins\Droptop\@Resources\GlobalVar\Control.inc"
@echo Beta Version Complete
attrib -h /s %5Redistributables\Basic-Version\Skins\Droptop Folders\desktop.ini"
attrib -s /d /s %5Redistributables\Basic-Version\Skins\Droptop Folders\Games\*"

RD /S /Q "%USERPROFILE%\Documents\GitHub\Droptop-Four\Droptop"
RD /S /Q "%USERPROFILE%\Documents\GitHub\Droptop-Four\Droptop Community Apps"
RD /S /Q "%USERPROFILE%\Documents\GitHub\Droptop-Four\Droptop Folders"
del /f "%USERPROFILE%\Documents\GitHub\Droptop-Four\*.zip"
del /f "%USERPROFILE%\Documents\GitHub\Droptop-Four\*.rmskin"

RD /S /Q "%USERPROFILE%\Documents\GitHub\Beta-Update\Droptop"
del /f "%USERPROFILE%\Documents\GitHub\Beta-Update\*.zip"
del /f "%USERPROFILE%\Documents\GitHub\Beta-Update\*.rmskin"

powershell.exe cd %5Redistributables"; Remove-Item '.\@Rmskins\Beta-Update\*.zip' -Recurse; Remove-Item '.\@Rmskins\Beta-Update\*.rmskin' -Recurse; .\MakeRmSkin.ps1 -Skin Beta-Update; Remove-Item '.\@Rmskins\Beta-Update\*.zip' -Recurse; Rename-Item -Path '.\@Rmskins\Beta-Update\Beta-Update.rmskin' -NewName 'Droptop_Beta_Update.rmskin'; cd ../; Copy-Item -Path '.\Droptop Community Apps\Apps\*\*.rmskin' -Destination '.\Redistributables\Droptop-Community-Apps\Apps' -Recurse

xcopy /E /I /Y %5Redistributables\@Rmskins\Beta-Update\*" "%USERPROFILE%\Documents\GitHub\Beta-Update\"
xcopy /E /I /Y %5Redistributables\Update\Skins\*" "%USERPROFILE%\Documents\GitHub\Beta-Update\"

attrib -h /s %5Droptop\@Resources\OriginalFolders\desktop.ini"
attrib -s /d /s %5Droptop\@Resources\OriginalFolders\Games\*"

%4 !WriteKeyValue Variables DroptopIsUpdate 0 %5Droptop\@Resources\GlobalVar\Control.inc"
%4 !WriteKeyValue Variables FirstLoad 1 %5Droptop\@Resources\GlobalVar\UserSettings.inc"

powershell.exe [console]::beep(500,100); [console]::beep(1200,120)

del /f /q %5Droptop Community Apps\Apps\CustomApp.ini"
del /f /q "%USERPROFILE%\Documents\GitHub\Community-Apps\CustomApp.ini"
del /f /q "%USERPROFILE%\GitHub\Droptop-Four\Droptop Community Apps\Apps\CustomApp.ini"
del /f /q "%USERPROFILE%\Documents\Rainmeter\Skins\Droptop\@Resources\Scripts\AppBuilder\Sample Apps\CustomApp.ini"
del /f /q "%USERPROFILE%\Documents\GitHub\Droptop-Four\Droptop\@Resources\Scripts\AppBuilder\Sample Apps\CustomApp.ini"

@echo All distributables finished successfully. Press any key to push Beta-Update to GitHub.

TIMEOUT 10

git config --global user.name "%USERNAME%"
git config --global user.email "N/A"

git config --global http.sslVerify false
cd "%USERPROFILE%\Documents\GitHub\Beta-Update"
git checkout main
git add .
git commit -m %2
git push
gh release create v%2 "%USERPROFILE%\Documents\GitHub\Beta-Update\Droptop_Beta_Update.rmskin" --latest --notes "See download link below (Droptop_Beta_Update.rmskin). See [Droptop Discord](https://discord.gg/droptop-four-800124057923485728) channel [#Preview-Updates](https://discord.com/channels/800124057923485728/801786468426973185) for change notes." --title "Droptop Update (Beta)"

git config --global http.sslVerify false
cd "%USERPROFILE%\Documents\GitHub\Community-Apps"
git checkout main
git add .
git commit -m %2
git push

attrib -h /s %5Droptop Folders\desktop.ini"
attrib +s /d /s %5Droptop Folders\Games\*"
attrib -s /s %5Droptop Folders\desktop.ini"
attrib +h /s %5Droptop Folders\desktop.ini"

"Wscript.exe" %5Droptop\@Resources\Scripts\IconsColor1.vbs" %5"

echo Start Time: %startTime%
echo Finish Time: %time%

powershell.exe [console]::beep(800,200); [console]::beep(800,320)
@echo Press any key to push all remaining versions to GitHub.
PAUSE
@echo Are you sure? Press any key to continue.
PAUSE

powershell.exe cd %5Redistributables"; Remove-Item '.\@Rmskins\Basic-Version\*.zip'; Remove-Item '.\@Rmskins\Supporter-Version\*.zip' -Recurse; Remove-Item '.\@Rmskins\Update\*.zip' -Recurse; Remove-Item '.\@Rmskins\Basic-Version\*.rmskin' -Recurse; Remove-Item '.\@Rmskins\Supporter-Version\*.rmskin' -Recurse; Remove-Item '.\@Rmskins\Update\*.rmskin' -Recurse; .\MakeRmSkin.ps1 -Skin Basic-Version; .\MakeRmSkin.ps1 -Skin Supporter-Version; .\MakeRmSkin.ps1 -Skin Update; Remove-Item '.\@Rmskins\Basic-Version\*.zip' -Recurse; Remove-Item '.\@Rmskins\Supporter-Version\*.zip' -Recurse; Remove-Item '.\@Rmskins\Update\*.zip' -Recurse; Rename-Item -Path '.\@Rmskins\Basic-Version\Basic-Version.rmskin' -NewName 'Droptop_Basic_Version.rmskin'; Rename-Item -Path '.\@Rmskins\Supporter-Version\Supporter-Version.rmskin' -NewName 'Droptop_Supporter_Version.rmskin'; Rename-Item -Path '.\@Rmskins\Update\Update.rmskin' -NewName 'Droptop_Update.rmskin'

xcopy /E /I /Y %5Redistributables\@Rmskins\Basic-Version\*" "%USERPROFILE%\Documents\GitHub\Droptop-Four\"
xcopy /E /I /Y %5Redistributables\@Rmskins\Update\*" "%USERPROFILE%\Documents\GitHub\Droptop-Four\"
xcopy /E /I /Y %5Redistributables\@Rmskins\Supporter-Version\*" "%USERPROFILE%\Documents\GitHub\Supporter-Version\"

xcopy /E /I /Y %5Redistributables\Basic-Version\Skins\*" "%USERPROFILE%\Documents\GitHub\Droptop-Four\"

git config --global http.sslVerify false
cd "%USERPROFILE%\Documents\GitHub\Droptop-Four"
git checkout main
git add .
git commit -m %2
git push
gh release create v%2 "%USERPROFILE%\Documents\GitHub\Droptop-Four\Droptop_Basic_Version.rmskin" "%USERPROFILE%\Documents\GitHub\Droptop-Four\Droptop_Update.rmskin" --latest --notes "# >>> :arrow_down: [Visit droptopfour.com to download](https://droptopfour.com/download/) :arrow_down: <<<" --title "Droptop Four"

git config --global http.sslVerify true

echo Start Time: %startTime%
echo Finish Time: %time%

powershell.exe [console]::beep(100,900); [console]::beep(200,820)
@echo All versions pushed successfully. Press any key to start Droptop setup...
PAUSE
%4 !WriteKeyValue Variables Page 0 %5Droptop\Other\Startup\Start.ini"
%4 !ActivateConfig "Droptop\Other\Startup" "Start.ini"