REM "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned" required to create RMSKIN files.

@echo Reseting configurations to default
attrib -h /s %4Droptop\@Resources\OriginalFolders\desktop.ini"
attrib -s /d /s %4Droptop\@Resources\OriginalFolders\Games\*"
"C:\Program Files\Rainmeter\Rainmeter.exe" !DeactivateConfigGroup DroptopSuite
"C:\Program Files\Rainmeter\Rainmeter.exe" !DeactivateConfig Droptop\DropdownBar\AppBar
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DroptopIsBeta 0 %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Supporter 0 %4Droptop\@Resources\GlobalVar\Supporter.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc1 "#SKINSPATH#Droptop Folders\PinnedApps" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc2 "#SKINSPATH#Droptop Folders\Games" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc3 "#SKINSPATH#Droptop Folders\Bookmarks" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc4 "#SKINSPATH#Droptop Folders\Control" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc6 "#SKINSPATH#Droptop Folders\CustomFolder1" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc7 "#SKINSPATH#Droptop Folders\CustomFolder2" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc8 "#SKINSPATH#Droptop Folders\CustomFolder3" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc9 "#SKINSPATH#Droptop Folders\CustomFolder4" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc10 "#SKINSPATH#Droptop Folders\CustomFolder5" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc11 "#SKINSPATH#Droptop Folders\CustomFolder6" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc12 "#SKINSPATH#Droptop Folders\CustomFolder7" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppID1 "Droptop_Store-Bunz" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppID2 "Daily_Quotes-Bunz" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppID3 "Usage_Monitor-Cariboudjan" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppID4 "Disks-Phan" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppID5 "YouTube-Cariboudjan" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppInstallDate1 %3" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppInstallDate2 %3" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppInstallDate3 %3" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppInstallDate4 %3" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppInstallDate5 %3" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Droptop_Store-Bunz 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Daily_Quotes-Bunz 2 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Usage_Monitor-Cariboudjan 3 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Disks-Phan 4 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables YouTube-Cariboudjan 5 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ReverseDarkLight 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables RecentFileFilter "" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables NowPlayingClipNum 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables GmailUsername "" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables GmailPassword "" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DeviceIsMobile 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DisplayIsLandscape 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AlarmHour 9 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AlarmMinute 30 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AlarmNum 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AlarmOFF 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PomoNum 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AutoAltHome 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ShowSeconds 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ShowSecondsBar 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SetColorByWallpaperOFF 0 %4Droptop\@Resources\Themes\1Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SetColorByWallpaperOFF 0 %4Droptop\@Resources\Themes\2Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SetColorByWallpaperOFF 0 %4Droptop\@Resources\Themes\3Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SetColorByWallpaperOFF 0 %4Droptop\@Resources\Themes\4Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarSections 0 %4Droptop\@Resources\Themes\1Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarSections 1 %4Droptop\@Resources\Themes\2Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarSections 0 %4Droptop\@Resources\Themes\3Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarSections 0 %4Droptop\@Resources\Themes\4Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarBlur 1 %4Droptop\@Resources\Themes\1Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarBlur 0 %4Droptop\@Resources\Themes\2Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarBlur 1 %4Droptop\@Resources\Themes\3Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarBlur 0 %4Droptop\@Resources\Themes\4Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarGradient 0 %4Droptop\@Resources\Themes\1Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarGradient 0 %4Droptop\@Resources\Themes\2Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarGradient 0 %4Droptop\@Resources\Themes\3Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarGradient 0 %4Droptop\@Resources\Themes\4Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideSupport 0 %4Droptop\Other\Settings\Settings.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables UnitsMetric 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideIcons 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderMouseOverTimeNum 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideSubIcons 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HomeColumn 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HomeRow 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomHomeButton 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HomeColorNum 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum1 "1" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum2 "1" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum3 "1" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum4 "1" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum5 "1" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum6 "1" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum7 "1" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum8 "1" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum9 "1" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum10 "1" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum11 "1" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum12 "1" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol1 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol2 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol3 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol4 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol5 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol6 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol7 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol8 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol9 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol10 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol11 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol12 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor1 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor2 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor3 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor4 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor5 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor6 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor7 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor8 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor9 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor10 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor11 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor12 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailNum 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailLink1 """""" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailAuthor1 """""" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailSubject1 """""" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailLink2 """""" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailAuthor2 """""" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailSubject2 """""" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailLink3 """""" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailAuthor3 """""" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailSubject3 """""" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailLink4 """""" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailAuthor4 """""" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailSubject4 """""" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DroptopDisplayMonitor "" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables UpdateAvailable 0 %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables UpdateCheckFrequency 2 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CrashDetected 0 %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AppCommandCount 1 %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Page 0 %4Droptop\Other\Startup\Start.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables IconsSymbolNum 0 %4Droptop\Other\Startup\Start.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarSectionsNum 0 %4Droptop\Other\Startup\Start.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables NoAnimationNum 0 %4Droptop\Other\Startup\Style.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideExtraButtonsVolume 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ActivateTrayNum #Win10Apps# %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DroptopSize 1.4 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables IconSize Medium %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopIconSize Medium %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopIconWH 32 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables IconW 32 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables IconH 32 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DPIOverride 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DPIRescaleOFF 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CurrentDesktopNum 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PreviousDesktopTotal 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AutohideDelayNum 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AutohideSpeedNum 2 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerNum 6 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerTypeNum 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AlbumMaskNum 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AlbumBlurGreyscale 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AlbumBlurTint "215,215,215" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerTitle0 "" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerArtist0 "" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerTitle1 "" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerArtist1 "" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerTitle2 "" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerArtist2 "" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables WebNowPlayingAlbumImage "" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables WebNowPlayingAlbumImage "" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables WebNowPlayingAlbumImage "" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AlwaysShowSongTitleOFF 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables NowPlayingCustomColor 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables NowPlayingColor "255,255,255" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables NowPlayingOpacity 255 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTimeCenter 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LanguageNum 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ThemeNum 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables BatterySaverON 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables BatteryPowerLowThreshold0 20 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Time24HourNum 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TimeFormatTypeNum 2 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CenterTimeFormatTypeNum 3 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DroptopDisplayNum 99 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DroptopDisplayMonitor "" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DroptopPriorityList "Not set" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables BacklightCompatibilityMode 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables IPAddress "N/A" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables WNPTooltipDismissed 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysIconSizeNum 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LegacyAppDrawer 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder1 1 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder2 2 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder3 3 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder4 4 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder5 5 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder6 6 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder7 7 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder8 8 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder9 9 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder10 10 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder11 11 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder12 12 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName1 #SideAppName1# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName2 #SideAppName2# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName3 #SideAppName3# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName4 #SideAppName4# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName5 #SideAppName5# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName6 #SideAppName6# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName7 #SideAppName7# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName8 #SideAppName8# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName9 #SideAppName9# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName10 #SideAppName10# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName11 #SideAppName11# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName12 #SideAppName12# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName13 #SideAppName13# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName14 #SideAppName14# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName15 #SideAppName15# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName16 #SideAppName16# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName17 #SideAppName17# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName18 #SideAppName18# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName19 #SideAppName19# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName20 #SideAppName20# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName21 #SideAppName21# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName22 #SideAppName22# %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot1 1 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot2 2 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot3 3 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot4 4 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot5 5 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot6 6 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot7 7 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot8 8 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot9 9 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot10 10 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot11 11 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot12 12 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot13 13 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot14 14 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot15 15 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot16 16 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot17 17 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot18 18 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot19 19 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot20 20 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot21 21 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot22 22 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosNewDesktop 1 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosAction 2 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosLanguage 3 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosAssistant 4 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosSearch 5 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosTime 6 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosAlarm 7 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosVolume 8 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosMail 9 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosWeather 10 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosBattery 11 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosWifi 12 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosDownloads 13 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosRecent 14 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosCopy 15 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosMOND 16 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosCustomApp1 17 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosCustomApp2 18 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosCustomApp3 19 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosCustomApp4 20 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosCustomApp5 21 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosAppDrawer 22 %4Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden1 0 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden2 0 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden3 0 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden4 0 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden5 0 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden6 0 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden7 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden8 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden9 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden10 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden11 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden12 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppNewDesktop 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppAction 0 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppSearch 0 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppTime 0 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppMail 0 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppAlarm 0 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppVolume 0 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppWeather 0 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppWifi 0 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppBattery 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppDownloads 0 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppRecent 0 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppCopy 0 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppMOND 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppLanguage 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppAppDrawer 0 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppAssistant 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppCustomApp1 0 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppCustomApp2 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppCustomApp3 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppCustomApp4 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppCustomApp5 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider1 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider2 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider3 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider4 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider5 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider6 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider7 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider8 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider9 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider10 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider11 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider12 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider13 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider14 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider15 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider16 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider17 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider18 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider19 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider20 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider21 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTopBarDivider22 1 %4Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomApp1UpdateAvailable 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomApp2UpdateAvailable 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomApp3UpdateAvailable 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomApp4UpdateAvailable 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomApp5UpdateAvailable 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DeviceIsNotTouch 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables BatteryBacklightIconOFF 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AltHome 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables UseVirtualDesktop 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LeftHotCornerActionNum 2 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables RightHotCornerActionNum 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables StretchCount 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideWinButton 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideProgramsApp 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppCommands 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideMailCount 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideGmailPreviews 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AHKNum 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables BarXposOffsetNum 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SearchModeNum 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DebugModeOFF 1 %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarWidth "#WORKAREAWIDTH#" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LocationLatitude "" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LocationLongitude "" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MyLocation "" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PreviousClipboard "" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables NumberOfItems 1 %4Droptop\Other\Apps\Downloads\Downloads.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables NumberOfItems 1 %4Droptop\Other\Apps\Recent\Recent.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables EnableDragDrop 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LargeHomeButton 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ZposFocused 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DisableDPINum 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DPIRescaleValue 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PopupInFullscreen 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Note1 "#NotesItem1#" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Note2 "#NotesItem2#" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Note3 "#NotesItem3#" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Note4 "#NotesItem4#" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Note5 "#NotesItem5#" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle1 "#FolderName1#" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle2 "#FolderName2#" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle3 "#FolderName3#" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle4 "#FolderName4#" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle5 "#FolderName5#" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle6 "#FolderName6#" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle7 "#FolderName7#" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle8 "#FolderName8#" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle9 "#FolderName9#" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle10 "#FolderName10#" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle11 "#FolderName11#" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle12 "#FolderName12#" %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LastFocusedApp "Explorer" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LastFocusedIM "Explorer.EXE" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LastFocusedTitle "" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ProcessPath "C:\WINDOWS\Explorer.EXE" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ProcessLoc "C:\WINDOWS\" %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ForceOpaque 0 %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ForceOpaqueON 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables RegionNum "1" %4Droptop\Other\WindowMenu\ThemeBuilder.Create.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CategoryNum "1" %4Droptop\Other\WindowMenu\ThemeBuilder.Create.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SubCatNum "1" %4Droptop\Other\WindowMenu\ThemeBuilder.Create.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables VarNum "1" %4Droptop\Other\WindowMenu\ThemeBuilder.Create.ini"
del /f /q %4Droptop\@Resources\Images\Media\Cover.png"
REM del /f /q %4Droptop\@Resources\Images\Media\CoverBlur.png"
call %4Droptop\@Resources\Scripts\LanguageScripts\RestoreFolders.bat" %4
reg add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" /v "#PROGRAMPATH#Rainmeter.exe" /t "REG_SZ" /d "" /f
cd %4Droptop\@Resources\Scripts\ImageMagick" & convert %4Droptop\Other\WindowMenu\WallpaperCache\Wallpaper0.png" "Wallpaper1.png" & convert %4Droptop\Other\WindowMenu\WallpaperCache\Wallpaper0.png" -crop 9999x100+0+0 "WallpaperCropped.png" & convert "WallpaperCropped.png" -blur 0x3 "Wallpaper1.0.png" & convert "WallpaperCropped.png" -blur 0x8 "Wallpaper1.1.png" & del /f /q "WallpaperCropped.png" & xcopy /E /I /Y "Wallpaper*.png" %4Droptop\Other\WindowMenu\WallpaperCache" & xcopy /E /I /Y "Wallpaper*.png" %4Droptop Folders\Other files\Themes" & del /f /q "*.png" & taskkill /f /im "convert.exe" & taskkill /f /im "mogrify.exe"
cd %4Droptop\@Resources\Scripts\Other"
REM xcopy /s /e /y /f /i %4Droptop" %4Redistributables\Droptop-Master"
@echo Creating Basic, Update, & Supporter versions...
TIMEOUT 10
del /f /q %4Droptop Folders\Other files\Themes\*.ttf"
del /f /q %4Droptop Folders\Other files\Themes\*.otf"
REM del /f /q %4Droptop Folders\Other files\Themes\Wallpaper1.*"
del /f /q %4Droptop\@Resources\Scripts\AppBuilder\@Rmskins\Droptop Apps\*"
del /f /q %4Droptop\@Resources\Scripts\AppBuilder\@Rmskins\Droptop Themes\*"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FirstLoad 0 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop Community Apps"
xcopy /e /y /f /i %4Droptop\@Resources\Scripts\Other\Layouts\*" %4Redistributables\Basic-Version\Layouts"
xcopy /e /y /f /i %4Droptop\@Resources\Scripts\Other\Layouts\*" %4Redistributables\Update\Layouts"
xcopy /e /y /f /i %4Droptop\@Resources\Scripts\Other\Plugins\*" %4Redistributables\Basic-Version\Plugins"
xcopy /e /y /f /i %4Droptop\@Resources\Scripts\Other\Plugins\*" %4Redistributables\Update\Plugins"
xcopy /e /y /f /i %4Droptop\@Resources\Scripts\Other\Plugins\*" %4Redistributables\Beta-Update\Plugins"
xcopy /e /y /f /i %4Redistributables\cli\*" %4Redistributables\Basic-Version\Skins\Meters on Demand"
xcopy /e /y /f /i %4Redistributables\cli\*" %4Redistributables\Update\Skins\Meters on Demand"
xcopy /e /y /f /i %4Redistributables\cli\*" %4Redistributables\Beta-Update\Skins\Meters on Demand"
RD /S /Q %4Redistributables\Basic-Version\Skins\Meters on Demand\.git"
RD /S /Q %4Redistributables\Update\Skins\Meters on Demand\.git"
RD /S /Q %4Redistributables\Beta-Update\Skins\Meters on Demand\.git"
xcopy /e /y /f /i %4Droptop\@Resources\Scripts\AppBuilder\TemplateBackup\*" %4Droptop\@Resources\Scripts\AppBuilder"
xcopy /e /i /y %4Droptop Community Apps" %4Redistributables\Basic-Version\Skins\Droptop Community Apps" /EXCLUDE:XcopyExclude.txt
robocopy %4Droptop" %4Redistributables\Basic-Version\Skins\Droptop" /E
robocopy %4Droptop\@Resources\OriginalFolders" %4Redistributables\Basic-Version\Skins\Droptop Folders" /E
REM "Wscript.exe" %4Droptop\@Resources\Scripts\IconsColor1.vbs" %4"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder12"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder11"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder10"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder9"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder8"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder7"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column1"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column2"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column3"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column4"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column5"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column6"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column7"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column8"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column9"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column10"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column11"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column12"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column13"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column14"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column15"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column16"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column17"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column18"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column19"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column1S"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column2S"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column3S"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column4S"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column5S"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column6S"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column7S"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column8S"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column9S"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column10S"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column11S"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column12S"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column13S"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column14S"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column15S"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column16S"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column17S"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column18S"
RD /S /Q %4Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column19S"
@echo Basic Version Complete
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FirstLoad 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Supporter 1 %4Droptop\@Resources\GlobalVar\Supporter.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Page 99 %4Droptop\Other\Startup\Start.ini"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop Community Apps"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop Folders"
robocopy %4Droptop" %4Redistributables\Supporter-Version\Skins\Droptop" /E
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\Icons"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\OriginalFolders"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder01"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder02"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder1"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder2"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder3"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder4"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder5"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder6"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\Other\Experiments"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\Other\WindowMenu"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\DropdownBar"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\Folders"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\Other\PowerMenu"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\Other\SettingsMenu"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\Other\Apps"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\Other\Tutorial\Tooltip"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\Other\Tutorial"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\Fonts"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\Images"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\Meters"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\Scripts"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\Sounds"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\Symbols"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\Calendars"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Alarm"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Battery"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Copy"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Downloads"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\MOND"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Mail"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Recent"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Search"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Volume"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Weather"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Wifi"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Action"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Desktops"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Language"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\AppDrawer"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Assistant"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Update"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\Languages"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\Other\BackgroundProcesses"
RD /S /Q %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\Themes"
del /f %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\Control.inc"
del /f %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\IncludedCommands.inc"
del /f %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\FolderSettings.inc"
del /f %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\TopBarPos.inc"
del /f %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\UserSettings.inc"
del /f %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\SettingsMenuOptions.inc"
del /f %4Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\ThemeBuilderOptions.inc"
@echo Supporter Version Complete
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FirstLoad 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Supporter 0 %4Droptop\@Resources\GlobalVar\Supporter.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Page 100 %4Droptop\Other\Startup\Start.ini"
RD /S /Q %4Redistributables\Update\Skins\Droptop"
robocopy %4Droptop" %4Redistributables\Update\Skins\Droptop" /E
@echo Update Version Complete
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DroptopIsBeta 1 %4Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FirstLoad 1 %4Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Supporter 0 %4Droptop\@Resources\GlobalVar\Supporter.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Page 100 %4Droptop\Other\Startup\Start.ini"
RD /S /Q %4Redistributables\Beta-Update\Skins\Droptop"
robocopy %4Droptop" %4Redistributables\Beta-Update\Skins\Droptop" /E
@echo Beta Version Complete
attrib -h /s %4Redistributables\Basic-Version\Skins\Droptop Folders\desktop.ini"
attrib -s /d /s %4Redistributables\Basic-Version\Skins\Droptop Folders\Games\*"
powershell.exe cd %4Redistributables"; Remove-Item '.\@Rmskins\Basic-Version\*.zip'; Remove-Item '.\@Rmskins\Supporter-Version\*.zip' -Recurse; Remove-Item '.\@Rmskins\Update\*.zip' -Recurse; Remove-Item '.\@Rmskins\Beta-Update\*.zip' -Recurse; Remove-Item '.\@Rmskins\Basic-Version\*.rmskin' -Recurse; Remove-Item '.\@Rmskins\Supporter-Version\*.rmskin' -Recurse; Remove-Item '.\@Rmskins\Update\*.rmskin' -Recurse; Remove-Item '.\@Rmskins\Beta-Update\*.rmskin' -Recurse; .\MakeRmSkin.ps1 -Skin Basic-Version; .\MakeRmSkin.ps1 -Skin Supporter-Version; .\MakeRmSkin.ps1 -Skin Update; .\MakeRmSkin.ps1 -Skin Beta-Update; Remove-Item '.\@Rmskins\Basic-Version\*.zip' -Recurse; Remove-Item '.\@Rmskins\Supporter-Version\*.zip' -Recurse; Remove-Item '.\@Rmskins\Update\*.zip' -Recurse; Remove-Item '.\@Rmskins\Beta-Update\*.zip' -Recurse; Rename-Item -Path '.\@Rmskins\Basic-Version\Basic-Version.rmskin' -NewName 'Droptop_Basic_Version.rmskin'; Rename-Item -Path '.\@Rmskins\Supporter-Version\Supporter-Version.rmskin' -NewName 'Droptop_Supporter_Version.rmskin'; Rename-Item -Path '.\@Rmskins\Update\Update.rmskin' -NewName 'Droptop_Update.rmskin'; Rename-Item -Path '.\@Rmskins\Beta-Update\Beta-Update.rmskin' -NewName 'Droptop_Beta_Update.rmskin'; cd ../; Copy-Item -Path '.\Droptop Community Apps\Apps\*\*.rmskin' -Destination '.\Redistributables\Droptop-Community-Apps\Apps' -Recurse

REM git config --global user.name "%USERNAME%"
REM git config --global user.email "N/A"

REM git config --global http.sslVerify false
REM cd "%USERPROFILE%\Documents\GitHub\Beta-Update"
REM git checkout main
REM git pull

REM git config --global http.sslVerify false
REM cd "%USERPROFILE%\Documents\GitHub\Droptop-Four"
REM git checkout main
REM git pull

RD /S /Q "%USERPROFILE%\Documents\GitHub\Basic-Version\Droptop"
RD /S /Q "%USERPROFILE%\Documents\GitHub\Basic-Version\Droptop Folders"
RD /S /Q "%USERPROFILE%\Documents\GitHub\Basic-Version\Droptop Community Apps"
RD /S /Q "%USERPROFILE%\Documents\GitHub\Supporter-Version\Droptop"
RD /S /Q "%USERPROFILE%\Documents\GitHub\Update\Droptop"
RD /S /Q "%USERPROFILE%\Documents\GitHub\Beta-Update\Droptop"

xcopy /E /I /Y %4Redistributables\@Rmskins\Basic-Version\*" "%USERPROFILE%\Documents\GitHub\Droptop-Four\"
xcopy /E /I /Y %4Redistributables\@Rmskins\Update\*" "%USERPROFILE%\Documents\GitHub\Droptop-Four\"
xcopy /E /I /Y %4Redistributables\@Rmskins\Beta-Update\*" "%USERPROFILE%\Documents\GitHub\Beta-Update\"
xcopy /E /I /Y %4Redistributables\@Rmskins\Supporter-Version\*" "%USERPROFILE%\Documents\GitHub\Supporter-Version\"

xcopy /E /I /Y %4Redistributables\Basic-Version\Skins\*" "%USERPROFILE%\Documents\GitHub\Droptop-Four\"
xcopy /E /I /Y %4Redistributables\Update\Skins\*" "%USERPROFILE%\Documents\GitHub\Beta-Update\"

REM "%USERPROFILE%\AppData\Local\GitHubDesktop\GitHubDesktop.exe"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Page 0 %4Droptop\Other\Startup\Start.ini"
attrib -h /s %4Droptop\@Resources\OriginalFolders\desktop.ini"
attrib -s /d /s %4Droptop\@Resources\OriginalFolders\Games\*"

powershell.exe [console]::beep(500,100); [console]::beep(1200,120)
@echo All distributables finished successfully. Press any key to push Beta-Update to GitHub.

TIMEOUT 10

git config --global user.name "%USERNAME%"
git config --global user.email "N/A"

git config --global http.sslVerify false
cd "%USERPROFILE%\Documents\GitHub\Beta-Update"
git checkout main
git pull
git add .
git commit -m %2
git push
gh release create v%2 "%USERPROFILE%\Documents\GitHub\Beta-Update\Droptop_Beta_Update.rmskin" --latest --notes "See download link below (Droptop_Beta_Update.rmskin). See [Droptop Discord](https://discord.gg/droptop-four-800124057923485728) channel [#Preview-Updates](https://discord.com/channels/800124057923485728/801786468426973185) for change notes." --title "Droptop Update (Beta)"

powershell.exe [console]::beep(800,200); [console]::beep(800,320)
@echo Press any key to push all remaining versions to GitHub.
PAUSE
@echo Are you sure? Press any key to continue.
PAUSE

git config --global http.sslVerify false
cd "%USERPROFILE%\Documents\GitHub\Droptop-Four"
git checkout main
git pull
git add .
git commit -m %2
git push
gh release create v%2 "%USERPROFILE%\Documents\GitHub\Droptop-Four\Droptop_Basic_Version.rmskin" "%USERPROFILE%\Documents\GitHub\Droptop-Four\Droptop_Update.rmskin" --latest --notes "# >>> :arrow_down: [Click here to update Droptop)](https://github.com/Droptop-Four/Droptop-Four/releases/latest/download/Droptop_Update.rmskin) :arrow_down: <<<" --title "Droptop Four"

git config --global http.sslVerify true
powershell.exe [console]::beep(100,900); [console]::beep(200,820)
@echo All versions pushed successfully. Press any key to start Droptop setup...
PAUSE

"C:\Program Files\Rainmeter\Rainmeter.exe" !ActivateConfig "Droptop\Other\Startup" "Start.ini"