@echo Reseting configurations to default
attrib -h /s %3Droptop\@Resources\OriginalFolders\desktop.ini"
attrib -s /d /s %3Droptop\@Resources\OriginalFolders\Games\*"
robocopy %3Redistributables\@Rmskins\Update" %3Redistributables\Archive\Droptop %1" /E
"C:\Program Files\Rainmeter\Rainmeter.exe" !DeactivateConfigGroup DroptopSuite
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Supporter 0 %3Droptop\@Resources\GlobalVar\Supporter.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc1 "#SKINSPATH#Droptop Folders\PinnedApps" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc2 "#SKINSPATH#Droptop Folders\Games" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc3 "#SKINSPATH#Droptop Folders\Bookmarks" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc4 "#SKINSPATH#Droptop Folders\Control" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc6 "#SKINSPATH#Droptop Folders\CustomFolder1" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc7 "#SKINSPATH#Droptop Folders\CustomFolder2" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc8 "#SKINSPATH#Droptop Folders\CustomFolder3" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc9 "#SKINSPATH#Droptop Folders\CustomFolder4" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc10 "#SKINSPATH#Droptop Folders\CustomFolder5" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc11 "#SKINSPATH#Droptop Folders\CustomFolder6" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc12 "#SKINSPATH#Droptop Folders\CustomFolder7" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppID1 "Disks-Phan" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppID2 "Quick_Settings-Cariboudjan" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppID3 "Usage_Monitor-Cariboudjan" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppID4 "Daily_Quotes-Bunz" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppID5 "Sample_App-Cariboudjan" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppInstallDate1 %2" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppInstallDate2 %2" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppInstallDate3 %2" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppInstallDate4 %2" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppInstallDate5 %2" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Disks-Phan 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Quick_Settings-Cariboudjan 2 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Usage_Monitor-Cariboudjan 3 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Daily_Quotes-Bunz 4 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Sample_App-Cariboudjan 5 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ReverseDarkLight 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables RecentFileFilter "" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables NowPlayingClipNum 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MondDevelopmentMode 0 %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables GmailUsername "Unassigned" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables GmailPassword "Password" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AlarmHour 9 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AlarmMinute 30 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AlarmNum 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AlarmOFF 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SetColorByWallpaperOFF 0 %3Droptop\@Resources\Themes\1Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SetColorByWallpaperOFF 0 %3Droptop\@Resources\Themes\2Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SetColorByWallpaperOFF 0 %3Droptop\@Resources\Themes\3Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SetColorByWallpaperOFF 0 %3Droptop\@Resources\Themes\4Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarSections 0 %3Droptop\@Resources\Themes\1Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarSections 1 %3Droptop\@Resources\Themes\2Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarSections 0 %3Droptop\@Resources\Themes\3Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarSections 0 %3Droptop\@Resources\Themes\4Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarBlur 1 %3Droptop\@Resources\Themes\1Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarBlur 0 %3Droptop\@Resources\Themes\2Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarBlur 1 %3Droptop\@Resources\Themes\3Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarBlur 0 %3Droptop\@Resources\Themes\4Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarGradient 0 %3Droptop\@Resources\Themes\1Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarGradient 0 %3Droptop\@Resources\Themes\2Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarGradient 0 %3Droptop\@Resources\Themes\3Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarGradient 0 %3Droptop\@Resources\Themes\4Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideSupport 0 %3Droptop\Other\Settings\Settings.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables UnitsMetric 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideIcons 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideSubIcons 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HomeColumn 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HomeRow 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomHomeButton 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HomeColorNum 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum1 "1" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum2 "1" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum3 "1" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum4 "1" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum5 "1" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum6 "1" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum7 "1" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum8 "1" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum9 "1" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum10 "1" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum11 "1" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderColorNum12 "1" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol1 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol2 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol3 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol4 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol5 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol6 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol7 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol8 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol9 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol10 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol11 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsSymbol12 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor1 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor2 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor3 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor4 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor5 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor6 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor7 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor8 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor9 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor10 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor11 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderIsColor12 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailNum 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailLink1 """""" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailAuthor1 """""" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailSubject1 """""" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailLink2 """""" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailAuthor2 """""" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailSubject2 """""" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailLink3 """""" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailAuthor3 """""" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailSubject3 """""" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailLink4 """""" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailAuthor4 """""" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailSubject4 """""" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DroptopDisplayMonitor "" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables UpdateAvailable 0 %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables UpdateCheckFrequency 2 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CrashDetected 0 %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AppCommandCount 1 %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Page 0 %3Droptop\Other\Startup\Start.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables IconsSymbolNum 0 %3Droptop\Other\Startup\Start.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarSectionsNum 0 %3Droptop\Other\Startup\Start.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables NoAnimationNum 0 %3Droptop\Other\Startup\Style.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideExtraButtonsVolume 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ActivateTrayNum #Win10Apps# %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DroptopSize 1.4 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables IconSize Medium %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopIconSize Medium %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopIconWH 32 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables IconW 32 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables IconH 32 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DPIOverride 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DPIRescaleOFF 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CurrentDesktopNum 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PreviousDesktopTotal 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AutohideDelayNum 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AutohideSpeedNum 2 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerNum 6 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerTypeNum 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AlbumMaskNum 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AlbumBlurGreyscale 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AlbumBlurTint "215,215,215" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerTitle0 "" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerArtist0 "" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerTitle1 "" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerArtist1 "" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerTitle2 "" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerArtist2 "" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables WebNowPlayingAlbumImage "" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables WebNowPlayingAlbumImage "" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables WebNowPlayingAlbumImage "" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AlwaysShowSongTitleOFF 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTimeCenter 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LanguageNum 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ThemeNum 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Time24HourNum 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DroptopDisplayNum 99 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DroptopDisplayMonitor "" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DroptopPriorityList "Not set" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables BacklightCompatibilityMode 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables IPAddress "N/A" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables WNPTooltipDismissed 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysIconSizeNum 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LegacyAppDrawer 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder1 1 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder2 2 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder3 3 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder4 4 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder5 5 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder6 6 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder7 7 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder8 8 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder9 9 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder10 10 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder11 11 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder12 12 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName1 #SideAppName1# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName2 #SideAppName2# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName3 #SideAppName3# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName4 #SideAppName4# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName5 #SideAppName5# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName6 #SideAppName6# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName7 #SideAppName7# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName8 #SideAppName8# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName9 #SideAppName9# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName10 #SideAppName10# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName11 #SideAppName11# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName12 #SideAppName12# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName13 #SideAppName13# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName14 #SideAppName14# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName15 #SideAppName15# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName16 #SideAppName16# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName17 #SideAppName17# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName18 #SideAppName18# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName19 #SideAppName19# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName20 #SideAppName20# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName21 #SideAppName21# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlotName22 #SideAppName22# %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot1 1 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot2 2 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot3 3 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot4 4 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot5 5 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot6 6 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot7 7 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot8 8 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot9 9 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot10 10 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot11 11 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot12 12 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot13 13 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot14 14 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot15 15 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot16 16 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot17 17 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot18 18 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot19 19 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot20 20 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot21 21 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppSlot22 22 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosNewDesktop 1 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosAction 2 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosLanguage 3 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosAssistant 4 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosSearch 5 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosTime 6 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosAlarm 7 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosVolume 8 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosMail 9 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosWeather 10 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosBattery 11 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosWifi 12 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosDownloads 13 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosRecent 14 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosCopy 15 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosMOND 16 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosCustomApp1 17 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosCustomApp2 18 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosCustomApp3 19 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosCustomApp4 20 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosCustomApp5 21 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SideAppPosAppDrawer 22 %3Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden1 0 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden2 0 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden3 0 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden4 0 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden5 0 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden6 0 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden7 1 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden8 1 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden9 1 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden10 1 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden11 1 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden12 1 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppNewDesktop 1 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppAction 0 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppSearch 0 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppTime 0 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppMail 0 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppAlarm 1 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppVolume 0 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppWeather 0 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppWifi 0 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppBattery 1 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppDownloads 0 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppRecent 0 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppCopy 1 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppMOND 1 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppLanguage 1 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppAppDrawer 0 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppAssistant 1 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppCustomApp1 0 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppCustomApp2 1 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppCustomApp3 1 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppCustomApp4 1 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppCustomApp5 1 %3Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomApp1UpdateAvailable 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomApp2UpdateAvailable 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomApp3UpdateAvailable 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomApp4UpdateAvailable 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomApp5UpdateAvailable 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TouchScreenModeOFF 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables BatteryBacklightIconOFF 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AltHome 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LeftHotCornerActionNum 2 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables RightHotCornerActionNum 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables StretchCount 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideWinButton 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideProgramsApp 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppCommands 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideMailCount 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideGmailPreviews 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AHKNum 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables BarXposOffsetNum 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SearchModeNum 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DebugModeOFF 1 %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarWidth "#WORKAREAWIDTH#" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LocationLatitude "" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LocationLongitude "" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MyLocation "" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables NumberOfItems 1 %3Droptop\Other\Apps\Downloads\Downloads.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables NumberOfItems 1 %3Droptop\Other\Apps\Recent\Recent.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables EnableDragDrop 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ZposFocused 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DisableDPINum 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DPIRescaleValue 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PopupInFullscreen 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Note1 "#NotesItem1#" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Note2 "#NotesItem2#" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Note3 "#NotesItem3#" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Note4 "#NotesItem4#" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Note5 "#NotesItem5#" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle1 "#FolderName1#" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle2 "#FolderName2#" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle3 "#FolderName3#" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle4 "#FolderName4#" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle5 "#FolderName5#" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle6 "#FolderName6#" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle7 "#FolderName7#" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle8 "#FolderName8#" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle9 "#FolderName9#" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle10 "#FolderName10#" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle11 "#FolderName11#" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle12 "#FolderName12#" %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LastFocusedApp "Explorer" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LastFocusedIM "Explorer.EXE" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LastFocusedTitle "" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ProcessPath "C:\WINDOWS\Explorer.EXE" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ProcessLoc "C:\WINDOWS\" %3Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables RegionNum "1" %3Droptop\Other\WindowMenu\ThemeBuilder.Create.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CategoryNum "1" %3Droptop\Other\WindowMenu\ThemeBuilder.Create.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SubCatNum "1" %3Droptop\Other\WindowMenu\ThemeBuilder.Create.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables VarNum "1" %3Droptop\Other\WindowMenu\ThemeBuilder.Create.ini"
del /f /q %3Droptop\@Resources\Images\Media\Cover.png"
REM del /f /q %3Droptop\@Resources\Images\Media\CoverBlur.png"
call %3Droptop\@Resources\Scripts\LanguageScripts\RestoreFolders.bat" %3
reg add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" /v "#PROGRAMPATH#Rainmeter.exe" /t "REG_SZ" /d "" /f
cd %3Droptop\@Resources\Scripts\ImageMagick" & convert %3Droptop\Other\WindowMenu\WallpaperCache\Wallpaper0.png" "Wallpaper1.png" & convert %3Droptop\Other\WindowMenu\WallpaperCache\Wallpaper0.png" -crop 9999x100+0+0 "WallpaperCropped.png" & convert "WallpaperCropped.png" -blur 0x3 "Wallpaper1.0.png" & convert "WallpaperCropped.png" -blur 0x8 "Wallpaper1.1.png" & del /f /q "WallpaperCropped.png" & xcopy /E /I /Y "Wallpaper*.png" %3Droptop\Other\WindowMenu\WallpaperCache" & xcopy /E /I /Y "Wallpaper*.png" %3Droptop Folders\Other files\Themes" & del /f /q "*.png" & taskkill /f /im "convert.exe" & taskkill /f /im "mogrify.exe"
cd %3Droptop\@Resources\Scripts\Other"
REM xcopy /s /e /y /f /i %3Droptop" %3Redistributables\Droptop-Master"
@echo Creating Basic, Update, & Supporter versions...
TIMEOUT 10
del /f /q %3Droptop Folders\Other files\Themes\*.ttf"
del /f /q %3Droptop Folders\Other files\Themes\*.otf"
REM del /f /q %3Droptop Folders\Other files\Themes\Wallpaper1.*"
del /f /q %3Droptop\@Resources\Scripts\AppBuilder\@Rmskins\Droptop Apps\*"
del /f /q %3Droptop\@Resources\Scripts\AppBuilder\@Rmskins\Droptop Themes\*"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FirstLoad 0 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop Community Apps"
xcopy /s /e /y /f /i %3Droptop\@Resources\Scripts\Other\Layouts\*" %3Redistributables\Basic-Version\Layouts"
xcopy /s /e /y /f /i %3Droptop\@Resources\Scripts\Other\Layouts\*" %3Redistributables\Update\Layouts"
xcopy /s /e /y /f /i %3Droptop\@Resources\Scripts\Other\Plugins\*" %3Redistributables\Basic-Version\Plugins"
xcopy /s /e /y /f /i %3Droptop\@Resources\Scripts\Other\Plugins\*" %3Redistributables\Update\Plugins"
xcopy /E /I /Y %3Droptop Community Apps" %3Redistributables\Basic-Version\Skins\Droptop Community Apps" /EXCLUDE:XcopyExclude.txt
robocopy %3Droptop" %3Redistributables\Basic-Version\Skins\Droptop" /E
robocopy %3Droptop\@Resources\OriginalFolders" %3Redistributables\Basic-Version\Skins\Droptop Folders" /E
REM "Wscript.exe" %3Droptop\@Resources\Scripts\IconsColor1.vbs" %3"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder12"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder11"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder10"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder9"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder8"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder7"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column1"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column2"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column3"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column4"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column5"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column6"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column7"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column8"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column9"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column10"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column11"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column12"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column13"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column14"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column15"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column16"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column17"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column18"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column19"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column1S"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column2S"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column3S"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column4S"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column5S"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column6S"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column7S"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column8S"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column9S"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column10S"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column11S"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column12S"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column13S"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column14S"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column15S"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column16S"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column17S"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column18S"
RD /S /Q %3Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column19S"
@echo Basic Version Complete
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FirstLoad 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Supporter 1 %3Droptop\@Resources\GlobalVar\Supporter.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Page 99 %3Droptop\Other\Startup\Start.ini"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop Community Apps"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop Folders"
robocopy %3Droptop" %3Redistributables\Supporter-Version\Skins\Droptop" /E
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\Icons"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\OriginalFolders"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder01"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder02"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder1"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder2"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder3"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder4"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder5"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder6"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\Other\Experiments"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\Other\WindowMenu"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\DropdownBar"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\Folders"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\Other\PowerMenu"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\Other\SettingsMenu"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\Other\Apps"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\Other\Tutorial\Tooltip"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\Other\Tutorial"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\Fonts"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\Images"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\Meters"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\Scripts"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\Sounds"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\Symbols"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\Calendars"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Alarm"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Battery"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Copy"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Downloads"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\MOND"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Mail"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Recent"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Search"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Volume"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Weather"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Wifi"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Action"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Desktops"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Language"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\AppDrawer"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Assistant"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Update"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\Languages"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\Other\BackgroundProcesses"
RD /S /Q %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\Themes"
del /f %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\Control.inc"
del /f %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\IncludedCommands.inc"
del /f %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\FolderSettings.inc"
del /f %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\TopBarPos.inc"
del /f %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\UserSettings.inc"
del /f %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\SettingsMenuOptions.inc"
del /f %3Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\ThemeBuilderOptions.inc"
@echo Supporter Version Complete
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FirstLoad 1 %3Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Supporter 0 %3Droptop\@Resources\GlobalVar\Supporter.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Page 100 %3Droptop\Other\Startup\Start.ini"
RD /S /Q %3Redistributables\Update\Skins\Droptop"
robocopy %3Droptop" %3Redistributables\Update\Skins\Droptop" /E
attrib -h /s %3Redistributables\Basic-Version\Skins\Droptop Folders\desktop.ini"
attrib -s /d /s %3Redistributables\Basic-Version\Skins\Droptop Folders\Games\*"
powershell.exe cd %3Redistributables"; Remove-Item '.\@Rmskins\Basic-Version\*.zip'; Remove-Item '.\@Rmskins\Supporter-Version\*.zip' -Recurse; Remove-Item '.\@Rmskins\Update\*.zip' -Recurse; Remove-Item '.\@Rmskins\Basic-Version\*.rmskin' -Recurse; Remove-Item '.\@Rmskins\Supporter-Version\*.rmskin' -Recurse; Remove-Item '.\@Rmskins\Update\*.rmskin' -Recurse; Remove-Item '.\@Rmskins\Beta-Update\*.rmskin' -Recurse; .\MakeRmSkin.ps1 -Skin Basic-Version; .\MakeRmSkin.ps1 -Skin Supporter-Version; .\MakeRmSkin.ps1 -Skin Update; Remove-Item '.\@Rmskins\Basic-Version\*.zip' -Recurse; Remove-Item '.\@Rmskins\Supporter-Version\*.zip' -Recurse; Remove-Item '.\@Rmskins\Update\*.zip' -Recurse; Rename-Item -Path '.\@Rmskins\Basic-Version\Basic-Version.rmskin' -NewName 'Droptop_Basic_Version.rmskin'; Rename-Item -Path '.\@Rmskins\Supporter-Version\Supporter-Version.rmskin' -NewName 'Droptop_Supporter_Version.rmskin'; Rename-Item -Path '.\@Rmskins\Update\Update.rmskin' -NewName 'Droptop_Update.rmskin'; Copy-Item '.\@Rmskins\Update\Droptop_Update.rmskin' -Destination '.\@Rmskins\Beta-Update'; Rename-Item -Path '.\@Rmskins\Beta-Update\Droptop_Update.rmskin' -NewName 'Droptop_Beta_Update.rmskin'; cd ../; Copy-Item -Path '.\Droptop Community Apps\Apps\*\*.rmskin' -Destination '.\Redistributables\Droptop Community Apps\Apps' -Recurse

RD /S /Q "%USERPROFILE%\Documents\GitHub\Basic-Version\Droptop"
RD /S /Q "%USERPROFILE%\Documents\GitHub\Basic-Version\Droptop Folders"
RD /S /Q "%USERPROFILE%\Documents\GitHub\Basic-Version\Droptop Community Apps"
RD /S /Q "%USERPROFILE%\Documents\GitHub\Supporter-Version\Droptop"
RD /S /Q "%USERPROFILE%\Documents\GitHub\Update\Droptop"
RD /S /Q "%USERPROFILE%\Documents\GitHub\Beta-Update\Droptop"

xcopy /E /I /Y %3Redistributables\@Rmskins\Basic-Version\*" "%USERPROFILE%\Documents\GitHub\Droptop-Four\"
xcopy /E /I /Y %3Redistributables\@Rmskins\Update\*" "%USERPROFILE%\Documents\GitHub\Droptop-Four\"
xcopy /E /I /Y %3Redistributables\@Rmskins\Beta-Update\*" "%USERPROFILE%\Documents\GitHub\Droptop-Four\"
xcopy /E /I /Y %3Redistributables\@Rmskins\Beta-Update\*" "%USERPROFILE%\Documents\GitHub\Beta-Update\"
REM xcopy /E /I /Y %3Redistributables\@Rmskins\Supporter-Version\*" "%USERPROFILE%\Documents\GitHub\Supporter-Version\"

xcopy /E /I /Y %3Redistributables\Basic-Version\Skins\*" "%USERPROFILE%\Documents\GitHub\Droptop-Four\"
xcopy /E /I /Y %3Redistributables\Update\Skins\*" "%USERPROFILE%\Documents\GitHub\Droptop-Four\"
xcopy /E /I /Y %3Redistributables\Update\Skins\*" "%USERPROFILE%\Documents\GitHub\Beta-Update\"
REM xcopy /E /I /Y %3Redistributables\Supporter-Version\Skins\*" "%USERPROFILE%\Documents\GitHub\Supporter-Version\"

"%USERPROFILE%\AppData\Local\GitHubDesktop\GitHubDesktop.exe"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Page 0 %3Droptop\Other\Startup\Start.ini"
attrib -h /s %3Droptop\@Resources\OriginalFolders\desktop.ini"
attrib -s /d /s %3Droptop\@Resources\OriginalFolders\Games\*"

powershell.exe [console]::beep(500,100); [console]::beep(1200,120)
@echo All distributables finished successfully. Press any key to push Beta-Update to GitHub.
PAUSE

cd "%USERPROFILE%\Documents\GitHub\Beta-Update"
git add .
git commit -m %1
git push
gh release create v%1 "%USERPROFILE%\Documents\GitHub\Beta-Update\Droptop_Beta_Update.rmskin" --latest --notes "See Discord for change notes." --title "Droptop Beta Update"

powershell.exe [console]::beep(800,200); [console]::beep(800,320)
@echo Press any key to push all remaining versions to GitHub.
PAUSE
@echo Are you sure? Press any key to continue.
PAUSE

cd "%USERPROFILE%\Documents\GitHub\Droptop-Four"
git add .
git commit -m %1
git push
gh release create v%1 "%USERPROFILE%\Documents\GitHub\Droptop-Four\*.rmskin" --latest --notes "See Discord for change notes." --title "Droptop Four"

powershell.exe [console]::beep(100,900); [console]::beep(200,820)
@echo All versions pushed successfully. Press any key to launch Droptop.
PAUSE

REM "C:\Program Files\Rainmeter\Rainmeter.exe" !ActivateConfig "Droptop\Other\Startup" "Start.ini"