[Variables]
; -------------------------------------------------------------------------------
; VariablesDefault.inc should contain all or most of the variables required for the app's function, especially user settings.
; VariablesDefault.inc keys and values are the default settings when the app is first installed or reinstalled.
; Any settings changed by the user should be written to Variables.inc, not VariablesDefault.inc.
; All keys in Variables.inc supercede the identical keys of VariablesDefault.inc. 
; VariablesDefault.inc acts as a backup and fallback.
; -------------------------------------------------------------------------------

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=ToolTipster-TheyCallMePapa
MyAppName=ToolTipster
MyAppAuthor=TheyCallMePapa
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\ToolTipster-TheyCallMePapa\Variables\Variables.inc
MyAppGUID=a55dddd9-e788-4503-a8ff-ca5017465a77

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------

ToolTipster0=1
ToolTipster1=0
ToolTipster2=0
ToolTipster3=0
ToolTipster4=0
ToolTipster5=0
ToolTipster6=0
ToolTipster7=0
ToolTipster8=0
ToolTipster9=0
ToolTipster10=0
ToolTipster11=0
ToolTipster12=0
ToolTipster13=0
