[Variables]
; -------------------------------------------------------------------------------
; VariablesDefault.inc should contain all or most of the variables required for the app's function, especially user settings.
; VariablesDefault.inc keys and values are the default settings when the app is first installed or reinstalled.
; Any settings changed by the user should be written to Variables.inc, not VariablesDefault.inc.
; All keys in Variables.inc supercede the identical keys of VariablesDefault.inc. 
; VariablesDefault.inc acts as a backup and fallback.
; -------------------------------------------------------------------------------

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=ToolTipster-TheyCallMePapa
MyAppName=ToolTipster
MyAppAuthor=TheyCallMePapa
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\ToolTipster-TheyCallMePapa\Variables\Variables.inc
MyAppGUID=a55dddd9-e788-4503-a8ff-ca5017465a77

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------

ToolTipster0=1
ToolTipster1=1
ToolTipster2=1
ToolTipster3=1
ToolTipster4=1
ToolTipster5=1
ToolTipster6=1
ToolTipster7=1
ToolTipster8=1
ToolTipster9=1
ToolTipster10=1
ToolTipster11=1
ToolTipster12=1
ToolTipster13=1
