[Rainmeter]

[Variables]

MyAppID=Game_Hub-Phan
MyAppName=Game Hub
MyAppAuthor=Phan
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\Game_Hub-Phan\Variables\Variables.inc

GameHub.FileLoc1=
GameHub.FileLoc2=
GameHub.FileLoc3=
GameHub.FileLoc4=
GameHub.FileLoc5=
GameHub.FileLoc6=
GameHub.FileLoc7=
GameHub.FileLoc8=
GameHub.FileLoc9=
GameHub.FileLoc10=
GameHub.FileLoc11=
GameHub.FileLoc12=

Box1Image=1
Box2Image=2
Box3Image=3
Box4Image=4
Box5Image=5
Box6Image=6
Box7Image=7
Box8Image=8
Box9Image=9
Box10Image=10
Box11Image=11
Box12Image=12

GameHub.RowsOfBoxes=3
GameHub.Boxes=3

GameHub.ImageScaleNum=1
GameHub.ImageScale1=150
GameHub.ImageScale2=200
GameHub.ImageScale3=250
GameHub.ImageScale4=300

GameHub.WHImageNum=2
GameHub.WidthImage1=150
GameHub.HeightImage1=195
GameHub.WidthImage2=200
GameHub.HeightImage2=260
GameHub.WidthImage3=250
GameHub.HeightImage3=325
GameHub.WidthImage4=300
GameHub.HeightImage4=390

GameHub.PlaySound=1
GameHub.Greyscale=0

GameHub.MenuWidth=((([#GameHub.WidthImage[#GameHub.WHImageNum]]-(#DropdownMenuCutout#*2))*3)+16)
