[Variables]

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=Daily_Quotes-Bunz
MyAppName=Daily Quotes
MyAppAuthor=Bunz
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\Daily_Quotes-Bunz\Variables\Variables.inc

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------

GetQuote=.*<item>.*<title>(.*)</title>.*<description>"(.*)"</description>

QuoteNumber=1
SwitchTime=20

AppName=Daily Quotes
AppAuthor=Bunz
AppVersion=1.0.3

Quote1=Change is the end result of all true learning.
Author1=Leo Buscaglia

Quote2=Laughter is the sun that drives winter from the human face.
Author2=Victor Hugo

Quote3=Start with what is right rather than what is acceptable.
Author3=Franz Kafka
Word1=back-form
Definition1=verb tr.: To make a word by dropping an apparent affix from a longer word.
HistoryDate1=1789
HistoryDesc1=New Jersey is 1st state to ratify Bill of Rights
Quote4=If you do not conquer self, you will be conquered by self.
Author4=Napoleon Hill
