[Variables]

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=Daily_Quotes-Bunz
MyAppName=Daily Quotes
MyAppAuthor=Bunz
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\Daily_Quotes-Bunz\Variables\Variables.inc

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------

GetQuote=.*<item>.*<title>(.*)</title>.*<description>"(.*)"</description>

QuoteNumber=1
SwitchTime=20

AppName=Daily Quotes
AppAuthor=Bunz
AppVersion=1.0.3

Quote1=There's a difference between a philosophy and a bumper sticker.
Author1=Charles M. Schulz

Quote2=The less we deserve good fortune, the more we hope for it.
Author2=Lucius Annaeus Seneca

Quote3=The human race has one really effective weapon, and that is laughter.
Author3=Mark Twain
Word1=argentocracy
Definition1=noun: 1. Rule by the wealthy. 2. Undue influence of money.
HistoryDate1=1529
HistoryDesc1=Thomas More appointed Lord Chancellor of England
Quote4=All wish to possess knowledge, but few, comparatively speaking, are willing to pay the price.
Author4=Juvenal
