[Variables]

DevicesNumber=7

Devices=Arctis Pro Wireless|44643149312662|Bluetooth#Bluetootha0:29:42:3a:cd:b0-28:9a:4b:0e:72:96|0|1|0|Audio/Video|Audio Video Wearable Headset|0|0|0;AirPods Pro - Find My|71141739493567|Bluetooth#Bluetootha0:29:42:3a:cd:b0-40:b3:fa:1c:78:bf|0|1|0|Audio/Video|Audio Video Headphones|0|0|0;Surface Slim Pen 2|234849569145700|BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-d5:98:2d:25:03:64|1|1|0|HumanInterfaceDevice|DigitalPen|1|100|1;Surface Arc Mouse|254394102878146|BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-e7:5e:be:22:8f:c2|0|1|0|HumanInterfaceDevice|Mouse|0|0|1;MX Master 2S|223463262609937|BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-cb:3d:18:63:62:11|0|1|0|HumanInterfaceDevice|Mouse|0|0|1;NVIDIA SHIELD Remote|79921510527776|BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-48:b0:2d:3e:b3:20|0|1|0|RemoteControl|Unknown|0|0|1;Logi M750 L|239457178165969|BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-d9:c8:f8:0b:22:d1|0|1|0|HumanInterfaceDevice|Mouse|0|0|1;

BTStatus=1

PageDevice1=1
PageDevice2=2
PageDevice3=3
PageDevice4=4
PageDevice5=5
PageDevice6=6
PageDevice7=7
PageDevice8=8

Device1Name=Arctis Pro Wireless
Device2Name=AirPods Pro - Find My
Device3Name=Surface Slim Pen 2
Device4Name=Surface Arc Mouse
Device5Name=MX Master 2S
Device6Name=NVIDIA SHIELD Remote
Device7Name=Logi M750 L
Device8Name=NVIDIA SHIELD Remote

Device1Address=44643149312662
Device2Address=71141739493567
Device3Address=234849569145700
Device4Address=254394102878146
Device5Address=223463262609937
Device6Address=79921510527776
Device7Address=239457178165969
Device8Address=79921510527776

Device1Id=Bluetooth#Bluetootha0:29:42:3a:cd:b0-28:9a:4b:0e:72:96
Device2Id=Bluetooth#Bluetootha0:29:42:3a:cd:b0-40:b3:fa:1c:78:bf
Device3Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-d5:98:2d:25:03:64
Device4Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-e7:5e:be:22:8f:c2
Device5Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-cb:3d:18:63:62:11
Device6Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-48:b0:2d:3e:b3:20
Device7Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-d9:c8:f8:0b:22:d1
Device8Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-48:b0:2d:3e:b3:20

Device1Connected=0
Device2Connected=0
Device3Connected=1
Device4Connected=0
Device5Connected=0
Device6Connected=0
Device7Connected=0
Device8Connected=0

Device1Paired=1
Device2Paired=1
Device3Paired=1
Device4Paired=1
Device5Paired=1
Device6Paired=1
Device7Paired=1
Device8Paired=1

Device1CanPair=0
Device2CanPair=0
Device3CanPair=0
Device4CanPair=0
Device5CanPair=0
Device6CanPair=0
Device7CanPair=0
Device8CanPair=0

Device1MajorCategory=Audio/Video
Device2MajorCategory=Audio/Video
Device3MajorCategory=HumanInterfaceDevice
Device4MajorCategory=HumanInterfaceDevice
Device5MajorCategory=HumanInterfaceDevice
Device6MajorCategory=RemoteControl
Device7MajorCategory=HumanInterfaceDevice
Device8MajorCategory=RemoteControl

Device1MinorCategory=Audio Video Wearable Headset
Device2MinorCategory=Audio Video Headphones
Device3MinorCategory=DigitalPen
Device4MinorCategory=Mouse
Device5MinorCategory=Mouse
Device6MinorCategory=Unknown
Device7MinorCategory=Mouse
Device8MinorCategory=Unknown

Device1HasBatteryLevel=0
Device2HasBatteryLevel=0
Device3HasBatteryLevel=1
Device4HasBatteryLevel=0
Device5HasBatteryLevel=0
Device6HasBatteryLevel=0
Device7HasBatteryLevel=0
Device8HasBatteryLevel=0

Device1Battery=0
Device2Battery=0
Device3Battery=100
Device4Battery=0
Device5Battery=0
Device6Battery=0
Device7Battery=0
Device8Battery=0

Device1IsBLE=0
Device2IsBLE=0
Device3IsBLE=1
Device4IsBLE=1
Device5IsBLE=1
Device6IsBLE=1
Device7IsBLE=1
Device8IsBLE=1

Color0=255,0,0,255
Color1=0,255,0,255
