[Variables]

DevicesNumber=4

Devices=AirPods Pro - Find My|71141739493567|Bluetooth#Bluetootha0:29:42:3a:cd:b0-40:b3:fa:1c:78:bf|0|1|0|Audio/Video|Audio Video Headphones|0|0|0;Surface Slim Pen 2|234849569145700|BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-d5:98:2d:25:03:64|0|1|0|HumanInterfaceDevice|DigitalPen|0|0|1;Surface Arc Mouse|254394102878146|BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-e7:5e:be:22:8f:c2|0|1|0|HumanInterfaceDevice|Mouse|0|0|1;NVIDIA SHIELD Remote|79921510527776|BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-48:b0:2d:3e:b3:20|0|1|0|RemoteControl|Unknown|0|0|1;

BTStatus=1

PageDevice1=1
PageDevice2=2
PageDevice3=3
PageDevice4=4
PageDevice5=5
PageDevice6=6
PageDevice7=7
PageDevice8=8

Device1Name=AirPods Pro - Find My
Device2Name=Surface Slim Pen 2
Device3Name=Surface Arc Mouse
Device4Name=NVIDIA SHIELD Remote
Device5Name=NVIDIA SHIELD Remote
Device6Name=MX Master 2S
Device7Name=Surface Slim Pen 2
Device8Name=Surface Slim Pen 2

Device1Address=71141739493567
Device2Address=234849569145700
Device3Address=254394102878146
Device4Address=79921510527776
Device5Address=79921510527776
Device6Address=223463262609936
Device7Address=234849569145700
Device8Address=234849569145700

Device1Id=Bluetooth#Bluetootha0:29:42:3a:cd:b0-40:b3:fa:1c:78:bf
Device2Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-d5:98:2d:25:03:64
Device3Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-e7:5e:be:22:8f:c2
Device4Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-48:b0:2d:3e:b3:20
Device5Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-48:b0:2d:3e:b3:20
Device6Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-cb:3d:18:63:62:10
Device7Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-d5:98:2d:25:03:64
Device8Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-d5:98:2d:25:03:64

Device1Connected=0
Device2Connected=0
Device3Connected=0
Device4Connected=0
Device5Connected=1
Device6Connected=0
Device7Connected=1
Device8Connected=0

Device1Paired=1
Device2Paired=1
Device3Paired=1
Device4Paired=1
Device5Paired=1
Device6Paired=1
Device7Paired=1
Device8Paired=1

Device1CanPair=0
Device2CanPair=0
Device3CanPair=0
Device4CanPair=0
Device5CanPair=0
Device6CanPair=0
Device7CanPair=0
Device8CanPair=0

Device1MajorCategory=Audio/Video
Device2MajorCategory=HumanInterfaceDevice
Device3MajorCategory=HumanInterfaceDevice
Device4MajorCategory=RemoteControl
Device5MajorCategory=RemoteControl
Device6MajorCategory=HumanInterfaceDevice
Device7MajorCategory=HumanInterfaceDevice
Device8MajorCategory=HumanInterfaceDevice

Device1MinorCategory=Audio Video Headphones
Device2MinorCategory=DigitalPen
Device3MinorCategory=Mouse
Device4MinorCategory=Unknown
Device5MinorCategory=Unknown
Device6MinorCategory=Mouse
Device7MinorCategory=DigitalPen
Device8MinorCategory=DigitalPen

Device1HasBatteryLevel=0
Device2HasBatteryLevel=0
Device3HasBatteryLevel=0
Device4HasBatteryLevel=0
Device5HasBatteryLevel=1
Device6HasBatteryLevel=0
Device7HasBatteryLevel=1
Device8HasBatteryLevel=0

Device1Battery=0
Device2Battery=0
Device3Battery=0
Device4Battery=0
Device5Battery=80
Device6Battery=0
Device7Battery=95
Device8Battery=0

Device1IsBLE=0
Device2IsBLE=1
Device3IsBLE=1
Device4IsBLE=1
Device5IsBLE=1
Device6IsBLE=1
Device7IsBLE=1
Device8IsBLE=1

Color0=255,0,0,255
Color1=0,255,0,255
