[Variables]

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=Disks-Phan
MyAppName=Disks
MyAppAuthor=Phan
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\Disks-Phan\Variables\Variables.inc

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------

disk1=C
disk2=D
disk3=E
disk4=P
disk5=Z

NumberOfDisks=3
